### ISSUE TITLE
Update WaterML 2 output

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#1]
Think this file is the transformation:
WOFpy/blob/master/wof/flask/templates/wml2_values_template.xml

**Comment by valentinedwv** [comment]
Template updated.
Once validated we will close

**Comment by valentinedwv** [comment]
Validation notes 2015-10-15:
Top 2 Codebase changes:

Description: cvc-datatype-valid.1.2.1: 'FPOC::12-Liquid aqueous' is not a valid value for 'NCName'.
These codes are internal to the document, so any old thing is good:
<gml:Definition gml:id="FPOC::12-Liquid aqueous">

Description: cvc-pattern-valid: Value 'mass %' is not facet-valid with respect to pattern '[^: \n\r\t]+' for type 'UomSymbol'.
These are going to need to be valid in the DB. Name, no spaces for GML:							
<wml2:uom code="mass %"/>


Template changes

Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/om/2.0":procedure}'. One of '{"http://www.opengis.net/om/2.0":resultTime}' is expected.
Ooops, need to enable resultTime, aka when this was generated:

			<om:procedure> 

			


Description: cvc-complex-type.2.4.b: The content of element 'wml2:timeZone' is not complete. One of '{"http://www.opengis.net/waterml/2.0":TimeZone}' is expected.

Description: cvc-complex-type.2.4.b: The content of element 'wml2:daylightSavingTimeZone' is not complete. One of '{"http://www.opengis.net/waterml/2.0":TimeZone}' is expected.
Dave needs to complete these:
					<wml2:timeZone ></wml2:timeZone>
					<wml2:daylightSavingTimeZone></wml2:daylightSavingTimeZone>


Description: cvc-pattern-valid: Value 'mass %' is not facet-valid with respect to pattern '[^: \n\r\t]+' for type 'UomSymbol'.
These are going to need to be valid in the DB. Name, no spaces for GML:							
<wml2:uom code="mass %"/>

**Comment by cdesyoun** [comment]
David, I think this template is not complete. We need to work on this. And in this template, I think the variable code that consists of three discriminators will be fixed, taking only the variable code.
First, can you work on this template? And then I will edit some elements.

**Comment by valentinedwv** [comment]
Have not run the schematron rules, but general items.

Times are invalid. Will need to pass in and create a function to format correctly.
```
		<wml2:DocumentMetadata gml:id="doc_md">
			<wml2:generationDate>2015-11-12 10:38:04.037897</wml2:generationDate>
```

```
                            <gml:TimePeriod gml:id="phen_time">
                                    <gml:beginPosition>2008-02-11 06:00:00</gml:beginPosition>
                                    <gml:endPosition>2008-04-30 06:00:00</gml:endPosition>
                            </gml:TimePeriod>
```
```
					<wml2:point>
						<wml2:MeasurementTVP>
							<wml2:time>2008-02-12 06:00:00</wml2:time>
							<wml2:value>430</wml2:value>

						</wml2:MeasurementTVP>
					</wml2:point>
```

====
need to add resultTime

Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/om/2.0":procedure}'. One of '{"http://www.opengis.net/om/2.0":resultTime}' is expected.

====
TimeZones need to be implemented, or ?
```
<wml2:MonitoringPoint>		
<!-- snip -->
			<wml2:verticalDatum xlink:href="http://www.opengis.net/def/datum/EPSG/0/5102" xlink:title="NGVD29"/>
					<wml2:timeZone ></wml2:timeZone>
					<wml2:daylightSavingTimeZone></wml2:daylightSavingTimeZone>
			</wml2:MonitoringPoint>
````

**Comment by valentinedwv** [comment]
Will need to be a link.
For now, we should point the href at the WOF11 rest endpoint, for the variable. not perfect, but functional.
			<om:observedProperty xlink:href="Discharge_cfs" xlink:title="Discharge"/>
