### ISSUE TITLE
ODM2 No EndDateTime for series

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#10]
endDateTime required.
For Timeseries TODAY ok.
 One Measurement make same as begin
(there are other TimeIntervalTypes we can use.

```XML
<variableTimeInterval xsi:type="TimeIntervalType">
   <beginDateTime>2015-04-28T00:00:00</beginDateTime>
</variableTimeInterval>
```
should be
```XML
                     <variableTimeInterval xsi:type="TimeIntervalType">
                        <beginDateTime>2008-01-01T00:00-06</beginDateTime>
                        <endDateTime>2008-04-30T00:00-06</endDateTime>
                     </variableTimeInterval>
```

**Comment by cdesyoun** [comment]
David, in ODM2, I took this data from the "Actions" table. In this case, "endDateTime" is optional.
When I looked at "WaterML.py", in the class, "class TimeIntervalType(TimePeriodType):", if there are no existed for "beginDateTime" and "endDateTime", they are not displayed.

**Comment by valentinedwv** [comment]
endDateTime required for waterML 1.x (Based on requests for users/developers)

For Timeseries TODAY ok, if it is not there. Ideally, it would be last measurement, so maybe an SQL script for timeseries. 

For Measurements, it can be degenerate (aka same start/end time).

so perhaps a an method in core to abstract and produce a WaterML.TimeIntervalType and replace line 480+

        #TimeInterval
        variableTimeInt = WaterML.TimeIntervalType(
            beginDateTime=beginDateTime,
            endDateTime=endDateTime)
        series.variableTimeInterval = variableTimeInt

**Comment by cdesyoun** [comment]
In the "core.py", I added these codes below:

```
        if beginDateTime is None:
            beginDateTime = datetime.datetime.now().isoformat()
        if endDateTime is None:
            endDateTime = datetime.datetime.now().isoformat()
```
