### ISSUE TITLE
installing from github repo master branch get an import error

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/WOFpy#104]
When installing from master I'm getting an import error

```python
ImportError: No module named examples.flask.odm2.timeseries.odm2_timeseries_dao
```

Operating system is ubuntu 16.04
pinging @lsetiawan

**Comment by miguelcleon** [comment]
actually 16.04

**Comment by lsetiawan** [comment]
@miguelcleon Please list the steps you take to install wofpy package. Thanks.

**Comment by miguelcleon** [comment]
Ok, I'm going to redo it first

**Comment by ocefpaf** [comment]
I tried:

```shell
git clone https://github.com/ODM2/WOFpy.git
cd WOFpy
conda create --yes -n WOFpy python=2.7 --file requirements.txt --file requirements-dev.txt
source activate WOFpy
python setup.py sdist
cd dist
pip install WOFpy-2.0.11b0.tar.gz
python -c "import wof; print(dir(wof))"
```

@miguelcleon can you try that and let us know what happens?

**Comment by miguelcleon** [comment]
I get ['WOF', 'WOF_1_1', 'WaterML', 'WaterML_1_1', 'WofWsdls', '_SERVICE_PARAMS', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'apps', 'core', 'core_1_0', 'core_1_1', 'site_map']

This command still gives an import error

python runserver_odm2_timeseries.py --config=odm2_config_timerseries.cfg --con
nection=connection2.file

`Traceback (most recent call last):
  File "runserver_odm2_timeseries.py", line 10, in <module>
    from wof.examples.flask.odm2.timeseries.odm2_timeseries_dao import Odm2Dao
ImportError: No module named examples.flask.odm2.timeseries.odm2_timeseries_dao`

**Comment by lsetiawan** [comment]
From @miguelcleon:

>now I'm getting other errors in the new code and the old code. Not sure why the old code is not working when it was working before.

> In the new code I'm getting an import error
ImportError: No module named examples.flask.odm2.timeseries.odm2_timeseries_dao

Looking at the actual code [runserver_odm2_timeseries.py](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/runserver_odm2_timeseries.py), this error doesn't seem to be coming from the actual since the import is actually `from wof.examples.flask.odm2.timeseries.odm2_timeseries_dao import Odm2Dao`.

**Comment by lsetiawan** [comment]
I have tested on same platform and not getting any error:
```
git clone https://github.com/ODM2/WOFpy.git
cd WOFpy/
conda create --yes -n wofpy -c conda-forge -c odm2 python=2.7 --file requirements.txt
source activate wofpy
python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install WOFpy-${version}.tar.gz && popd
```

**Comment by ocefpaf** [comment]
@miguelcleon I also tested and I did not get the error. Can you send us the result of:

```
python -c "import wof; print(wof.__file__)"
```

PS: I only tested the call b/c I don't have the `odm2_config_timerseries.cfg` and `connection2.file` files. But that results in an error after the imports/

**Comment by miguelcleon** [comment]
ok I ran @lsetiawan commands which include running setup.py and I got a different error

```
Traceback (most recent call last):
  File "runserver_odm2_timeseries.py", line 5, in <module>
    import wof.flask
ImportError: No module named wof.flask
```
Then running what @ocefpaf asked: 
```
 python -c "import wof; print(wof.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named wof
```

**Comment by lsetiawan** [comment]
@miguelcleon like I suspect, somehow wofpy is actually not installed in your conda environment.. hmm..

**Comment by miguelcleon** [comment]
yeah, it wasn't I hadn't ran the setup.py afterall 

now I get 
Then running what @ocefpaf asked:
```

python -c "import wof; print(wof.__file__)"
/home/miguelcleon/miniconda2/envs/wofpy3/lib/python2.7/site-packages/wof/__init__.pyc

```

but then 
```

python runserver_odm2_timeseries.py --config=odm2_config_timerseries.
cfg --connection=connection2.file
Namespace(config='odm2_config_timerseries.cfg', connection=<open file 'connection2.file', mode 'r' at 0x7f12ace01a50>, port=8080)
Traceback (most recent call last):
  File "runserver_odm2_timeseries.py", line 54, in <module>
    startServer(config=args.config,connection=args.connection,openPort=args.port)
...

backports.configparser.NoSectionError: No section: 'WOF'
```

**Comment by miguelcleon** [comment]
updated the last comment with the entire traceback

**Comment by ocefpaf** [comment]
> updated the last comment with the entire traceback

Thanks, that helps!

> backports.configparser.NoSectionError: No section: 'WOF'

Can you share the necessary files to reproduce that run? I want to be sure if the issue is `backports.configparser` or something else. If so we may need to re-think the strategy to update the code :unamused:

**Comment by miguelcleon** [comment]
Ok, I'll change the database to a test db in the connection file, how should I share it? Can I just email it to you guys?

**Comment by ocefpaf** [comment]
> Can I just email it to you guys?

That is fine. Ideally I would like the smallest config/files that reproduces the problem so we can use it as a test on Travis-CI.

**Comment by lsetiawan** [comment]
@ocefpaf What happened to conda-forge channel?
```
conda create --yes -n wofpy -c conda-forge -c odm2 python=2.7 --file requirements.txt
Fetching package metadata ...

CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: 00:00.330700
CF-RAY: 3553da52e80a7967-SEA

An remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```

**Comment by ocefpaf** [comment]
It is not `conda-forge` but all of anaconda.org at this moment. We need to wait until the service is back up...

**Comment by lsetiawan** [comment]
K. It's back. I guess the cloud is not always up, sometimes it rains; server down. 😉

**Comment by lsetiawan** [comment]
@miguelcleon So I did your steps and having no problem:

```
python runserver_odm2_timeseries.py --config=odm2_config_timeseries.cfg --connection=connection.file
Namespace(config='odm2_config_timeseries.cfg', connection=<open file 'connection.file', mode 'r' at 0x7f216a8cd540>, port=8080)
----------------------------------------------------------------
Access Service endpoints at 
http://127.0.0.1:8080/odm2timeseries/
http://127.0.0.1:8080/odm2timeseries/rest_1_0/
http://127.0.0.1:8080/odm2timeseries/rest_1_1/
http://127.0.0.1:8080/odm2timeseries/rest_2/
----------------------------------------------------------------
Namespace(config='odm2_config_timeseries.cfg', connection=<open file 'connection.file', mode 'r' at 0x7f8ae5965540>, port=8080)
----------------------------------------------------------------
Access Service endpoints at 
http://127.0.0.1:8080/odm2timeseries/
http://127.0.0.1:8080/odm2timeseries/rest_1_0/
http://127.0.0.1:8080/odm2timeseries/rest_1_1/
http://127.0.0.1:8080/odm2timeseries/rest_2/
----------------------------------------------------------------
```

@miguelcleon I noticed that you misspelled `timeseries` 
>python runserver_odm2_timeseries.py --config=odm2_config_timerseries.
cfg --connection=connection2.file

is your `.cfg` supposed to be called `odm2_config_timerseries.cf` or `odm2_config_timeseries.cfg`

**Comment by miguelcleon** [comment]
Wow, yes. That fixed it, odm2_config_timerseries.cfg is a typo it was supposed to be odm2_config_timeseries.cfg

Well certainly a more friendly error, would be useful here.
