### ISSUE TITLE
Example CSV model bad iso date

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#11]
Example CSV model producing invalid dateTime, no seconds

class Series(wof_base.BaseSeries):
    # Properties common to all series in this example
    BeginDateTime = '2008-01-01T00:00-06
    EndDateTime = '2008-04-30T00:00-06'

Needs to be:
  # Properties common to all series in this example
    BeginDateTime = '2008-01-01T00:00:00-06:00'
    EndDateTime = '2008-04-30T00:00:00-06:00'

**Comment by cdesyoun** [comment]
Yes, When testing this example before, I got the error for the time format.
I updated it now.
