### ISSUE TITLE
Add additional ouput formats

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#12]
EarthChemXML
WQX

Prototype OGC hydrodomain working group Water Quality Standards

Dependency: switching to spyne

**Comment by emiliom** [comment]
But is that in the scope of a WOF server? Maybe you're a few steps ahead and are thinking of generalizing WOFpy to serve different types of request protocols and response encodings?

**Comment by valentinedwv** [comment]
right move to WS.
