### ISSUE TITLE
Incorrect querying of affiliation in TimeSeries DAO

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#129]
This issue is to discuss [comment list item 3](https://github.com/ODM2/WOFpy/issues/128#issue-230810014) in #128

Curently, the DAO uses:
```python
db_session.query(odm2_models.Affiliations).\
filter(odm2_models.Affiliations.OrganizationID == r[i].FeatureActionObj.ActionObj.MethodObj.OrganizationID).first()  # noqa
```
to get Affiliations Object from results. This resulted in `None` for MySQL Little Bear site code: `USU-LBR-Mendon` which is incorrect, because there is an Affiliation. 

I've modified the query to:
```python
db_session.query(odm2_models.Affiliations).\
join(odm2_models.ActionBy).\
filter(odm2_models.ActionBy.ActionID == r[i].FeatureActionObj.ActionID).first()
```
and it is now giving me an Affiliations object:
**Note: I've modified the information for information safety reasons**
```python
<Affiliations({'PrimaryEmail': u'someemail@whatever.com', '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fa93bf7ed50>, 'PersonID': 1L, 'IsPrimaryOrganizationContact': True, 'PrimaryAddress': u'Somecooladress', 'OrganizationID': 1L, 'PrimaryPhone': u'1-555-555-5555', 'AffiliationEndDate': None, 'PersonLink': None, 'AffiliationStartDate': datetime.date(2015, 10, 9), 'AffiliationID': 1L})>
```

For reference: https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L226

@emiliom Let me know if that new query looks good. I used ActionBy to get affiliations instead of methods.

**Comment by lsetiawan** [comment]
Here's the actual SQL query of the new query to get Affiliations:
```SQL
SELECT odm2.affiliations.affiliationid AS odm2_affiliations_affiliationid, 
odm2.affiliations.personid AS odm2_affiliations_personid, 
odm2.affiliations.organizationid AS odm2_affiliations_organizationid,
odm2.affiliations.isprimaryorganizationcontact AS odm2_affiliations_isprimaryorganizationcontact,
odm2.affiliations.affiliationstartdate AS odm2_affiliations_affiliationstartdate,
odm2.affiliations.affiliationenddate AS odm2_affiliations_affiliationenddate,
odm2.affiliations.primaryphone AS odm2_affiliations_primaryphone,
odm2.affiliations.primaryemail AS odm2_affiliations_primaryemail, 
odm2.affiliations.primaryaddress AS odm2_affiliations_primaryaddress, 
odm2.affiliations.personlink AS odm2_affiliations_personlink 
FROM odm2.affiliations 
INNER JOIN odm2.actionby 
    ON odm2.affiliations.affiliationid = odm2.actionby.affiliationid 
WHERE odm2.actionby.actionid = %s
```

**Comment by emiliom** [comment]
> This resulted in None for MySQL Little Bear site code: USU-LBR-Mendon which is incorrect, because there is an Affiliation.

Didn't you say there were no affiliations in the MySQL LBR database??

The modified query looks good, and the confirmation that it works with the MySQL db is indication that it'll work with the postgresql EnviroDIY DB as well. The query looks pretty conventional, so I expect it to work fine on postgresql. Good job!

Go ahead and test it with the postgresql DB, and if the test looks good, submit a PR and I'll approve it today. Remember to change the `affiliations.organizationid = 1` values to Null, so the DB is back to where it was originally.

Then, in the rest of the day, try to update the cloud instance with the new master code.

The SQL code you just posted looks good. But like I said, the SQLAlchemy code already looked good.

**Comment by lsetiawan** [comment]
> Didn't you say there were no affiliations in the MySQL LBR database??

I thought there wasn't because I used that old query, but didn't actually checked on the database side.

**Comment by emiliom** [comment]
>> Didn't you say there were no affiliations in the MySQL LBR database??
> 
> I thought there wasn't because I used that old query, but didn't actually checked on the database side.

Ok. I thought you had directly confirmed it by looking at the affiliations table directly. Never trust a query you don't understand or can't confirm is working properly.

**Comment by emiliom** [comment]
Once you've updated the wofpy services on the amazon cloud and I've had a chance to test it and see the `Sources` in the response (I assume it's now there?!), I'll close this issue.

**Comment by emiliom** [comment]
@lsetiawan Woo-hoo, the "source" (affiliation/organization) information is now showing up on the `GetValues` responses for both the MySQL LBR and postgresql EnviroDIY!! eg, from the MySQL LBR:
```xml
<source sourceID="1">
  <organization>
    Utah State University Utah Water Research Laboratory
  </organization>
  <sourceDescription>
    Continuous water quality monitoring by Utah State University as part of the USDA CEAP Grant
  </sourceDescription>
<sourceLink>http://www.bearriverinfo.org</sourceLink>
</source>
```

I don't see "contact" (person) information, though. I suspect something still needs to be tweaked in the dao or the sqlalchemy model. Please look into it, but let me know if you don't know what's going on. Don't spend a lot of time feeling lost! The problem may be elsewhere.

**Comment by lsetiawan** [comment]
Hmm... That's strange because contactName should be there: https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L211

I'll try changing the string concatenation to `.format`.

**Comment by emiliom** [comment]
Well, the problem may be on the [wofpy generation of the contact info in the XML response](https://github.com/ODM2/WOFpy/blob/master/wof/WaterML_1_1.py) ... If you can confirm that contactName is being populated properly, we can look into that possibility; and probably leave that fix to a future release.

**Comment by lsetiawan** [comment]
I can confirm that the problem is not in https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L211 

So it is somewhere else. I will do some more debugging in [wofpy generation of the contact info in the XML response](https://github.com/ODM2/WOFpy/blob/master/wof/WaterML_1_1.py) to see if it's there.

**Comment by lsetiawan** [comment]
After digging into the code, it seems like the problem lies on https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L608

The contact information only shows if there is `sourceResult.Address`, `sourceResult.City`, `sourceResult.State`, and `sourceResult.ZipCode`, which based on https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L217 none of those keys are correct. I will try to fix this and see if that works.

**Comment by emiliom** [comment]
Yes, that all makes sense! I had seen that code and something didn't look right, but I didn't catch the indentation level on https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L618

Great!

**Comment by lsetiawan** [comment]
Futher changes to `core_1_1.py` allows contactInformation to show up, but for some reason email is split weirdly. **Note: Name has been changed**
```XML
<source sourceID="58">
<organization>The Nature Conservancy</organization>
<sourceDescription>
The Nature Conservancy is the leading conservation organization working around the world to protect ecologically important lands and waters for nature and people.
</sourceDescription>
<contactInformation>
<contactName>Kim Lastname</contactName>
<email>k</email>
<email>i</email>
<email>m</email>
<email>.</email>
<email>L</email>
<email>a</email>
<email>s</email>
<email>t</email>
<email>n</email>
<email>a</email>
<email>m</email>
<email>e</email>
<email>@</email>
<email>e</email>
<email>x</email>
<email>e</email>
<email>.</email>
<email>o</email>
<email>r</email>
<email>g</email>
</contactInformation>
<sourceLink/>
</source>
```

**Comment by emiliom** [comment]
Weird. But you're almost there.

**Comment by lsetiawan** [comment]
> What do you mean by this: "Note: Name has been changed"?

Just for identity security i guess, don't wanna reveal the actual result here. 😄
