### ISSUE TITLE
Enhancement to wof/wofpy_config.py

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/WOFpy#132]
From @emiliom:

> @ocefpaf completes enhancements of wof/wofpy_config.py, as described in #72: *wofpy_config.py will take two additional arguments (it already takes the copy-to file path): the "example" to be copied; and the deployment type (test vs "production" or test vs "server"). This also involves copying files into a "base" folder that could be hard-wired to be named wofpy, or be user-selectable (@lsetiawan can explain)

A few comments:

- I don't recommend the folder name to be `wofpy`. That can be troublesome with importing code because Python will search `import wofpy` in that folder first. Right now the folder is a mandatory argument of the CLI and I prefer to keep it that way. Users should always be in control of folder/file creation.

- Taking two additional arguments

So the new options are `production` vs `server` right? Not sure what that entails yet. Reading the past issues to get back on speed in the topic.

(I plan to work on this the whole day today and tomorrow.)

**Comment by emiliom** [comment]
> So the new options are `production` vs `server` right? 

Well, it's actually `test` vs (`production` or `server`). @lsetiawan and I couldn't decide which label of those two (`production` or `server`) makes the most sense. But we want to be consistent across the board. Right now we're using the label `production` in this newish directory: [wof/examples/production_configs](https://github.com/ODM2/WOFpy/tree/master/wof/examples/production_configs). So, I guess we're leaning towards `production`? What do you think, @lsetiawan?

> Not sure what that entails yet. 

@lsetiawan can help you to understand this, but unfortunately not so much today. Thursdays he works on another project, with another PI.

> I don't recommend the folder name to be `wofpy`. That can be troublesome with importing code because Python will search import wofpy in that folder first.

I understand. I think the main thing since we last talked is that we're now making a strong recommendation that a "base" folder should be used, b/c multiple DAO instances can then be put in that folder and it'll make more sense to users (from an organizational perspective) to have them in one place. But yes, the name of that base folder doesn't have to `wofpy` proper. Still, I think it'll be helpful to come up with a recommended name that's used in our sample configuration files and in the documentation, but that doesn't add the risk/conflict you're referring to (same name as package name). eg, "wofpyserver"?

@lsetiawan and I can help you understand this new approach, but again, not today! Maybe you can get up to speed today, and we can be more helpful tomorrow?

**Comment by emiliom** [comment]
FYI, I'll be tied up today, too.

**Comment by lsetiawan** [comment]
> Right now we're using the label production in this newish directory: wof/examples/production_configs. So, I guess we're leaning towards production? What do you think, @lsetiawan?

Yea, I like production better because `server` doesn't seem to really say much about the state of the application on a server.

> @lsetiawan and I can help you understand this new approach, but again, not today! Maybe you can get up to speed today, and we can be more helpful tomorrow?

@ocefpaf Let me know if you have any questions. 😄

**Comment by ocefpaf** [comment]
> wofpyserver

👍 

So the new options will be `test` and `production`, right?

>@ocefpaf Let me know if you have any questions.

I need to know what should happen for each option, for example what files should be copied?
Do you want to have a `default` one or those options should be a mandatory argument?

**Comment by lsetiawan** [comment]
> So the new options will be test and production, right?

Yep!

> I need to know what should happen for each option, for example what files should be copied?
Do you want to have a default one or those options should be a mandatory argument?

### Production
Should have basically everything in `timeseries` folder plus `production_configs`

### Test
Just the `timeseries` folder

Default I think should just be a test. Thanks.

**Comment by ocefpaf** [comment]
Perfect! Working on it. Thanks!!

**Comment by emiliom** [comment]
Thanks, guys. A couple of things to keep in mind:

- Running `wofpy_config.py` installs one DAO (eg, odm2/timeseries). The first time it's run, it'll create the base folder (eg, "wofpyserver") and the DAO sub-folder under it. Next time it's run (to install another DAO), if the user picks the existing base folder (eg, "wofpyserver"), obviously it should use it and not delete it ;)
- @lsetiawan, did we make a definitive decision on where `production_configs` should go?? Is it generic enough that there can be a single one, say, under the base folder? Or does it need to go under the DAO folder? If it's the former, it means running `wofpy_config.py` again won't result in copying `production_configs` again.

**Comment by lsetiawan** [comment]
> @lsetiawan, did we make a definitive decision on where production_configs should go?? Is it generic enough that there can be a single one, say, under the base folder?

I thought the current location for `production_configs` is the place we decided so it's generic.

**Comment by emiliom** [comment]
> I thought the current location for production_configs is the place we decided 

I don't follow. Maybe you mean the current location in your amazon cloud instance?? If so, I don't have access to it, so I don't know how you're organizing these folders.

> so it's generic.

Ok, so that means we're recommending a single directory, outside the DAO directory? eg:
```
wofpyserver
    |
    |---- production_configs
    |
    |---- odm2timeseries
    |
    |---- csvdao
    |
    |.....
```

**Comment by lsetiawan** [comment]
> I don't follow. Maybe you mean the current location in your amazon cloud instance?? If so, I don't have access to it, so I don't know how you're organizing these folders.

I thought you are talking about the location within the wof package. Sorry.. misunderstood.

> Ok, so that means we're recommending a single directory, outside the DAO directory? eg:

I like that example. Do you think that maybe `.cfg` goes in its own folder or just let the user move those outside the main folder that contains the dao and runserver script?

**Comment by emiliom** [comment]
>> I don't follow. Maybe you mean the current location in your amazon cloud instance?? If so, I don't have access to it, so I don't know how you're organizing these folders.
>
> I thought you are talking about the location within the wof package. Sorry.. misunderstood.

No problem. So, where did you place `production_configs` in your amazon instance? Right under the base folder, as in my example? Or within the dao folder?

I think you **are** recommending/agreeing that it go outside the DAO, right?

> I like that example. Do you think that maybe `.cfg` goes in its own folder or just let the user move those outside the main folder that contains the dao and runserver script?

That's the DAO `.cfg`, right? I don't remember, but the user doesn't have to then move the `.cfg` file to get wofpy to work, right? If so, `wofpy_config.py` shouldn't do anything special with it. It'll copy the entire DAO folder. 

Then our documentation will make the recommendation that for extra security it's best to move the `.cfg` file somewhere that's not web-accessible. But that'll be up to the user.

Does that make sense?

**Comment by lsetiawan** [comment]
> where did you place production_configs in your amazon instance? Right under the base folder, as in my example? Or within the dao folder?

I placed only `wofpy.ini` and `wsgi.py` within the [dao folder](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBR_installation.md#setup-wsgipy), and the rest of the files to their appropriate folders. 

> I think you are recommending/agreeing that it go outside the DAO, right?

Only certain parts.. please see my comment above.

> Then our documentation will make the recommendation that for extra security it's best to move the .cfg file somewhere that's not web-accessible. But that'll be up to the user.

Yea this makes sense. Sounds like a good idea.

**Comment by emiliom** [comment]
>> where did you place production_configs in your amazon instance? Right under the base folder, as in my example? Or within the dao folder?
>
> I placed only wofpy.ini and wsgi.py within the dao folder, and the rest of the files to their appropriate folders.
>
>> I think you are recommending/agreeing that it go outside the DAO, right?
>
> Only certain parts.. please see my comment above.

Ok. I think you should compose specific, clear directions to @ocefpaf about what `wofpy_config.py` should do with the `production_configs` folder and its content for a `production` deployment. It sounds like the most user-friendly thing would be to copy some of its files into the DAO folder, and copy the other files elsewhere (?); the user would then move/copy them manually to "their appropriate folders", per the instructions in the installation documentation. Or `production_configs` could be copied whole into the base folder, and then the user does all the manual copying of individual files per the instructions.

**Comment by lsetiawan** [comment]
> production_configs could be copied whole into the base folder, and then the user does all the manual copying of individual files per the instructions.

This is what I did on my instruction.

I think the easiest way to do this might be just to copy the whole `production_configs` folder. Like the example above and with instructions the user then move the nginx and systemd stuff to their appropriate folders. 

I already have instructions for this approach and I don't think it would take much for users to move files around.

**Comment by emiliom** [comment]
@ocefpaf, how is this going?

**Comment by ocefpaf** [comment]
Stuck. There is a lot on my plate due to the travelling. I should have something late Thursdays or early Friday.

**Comment by emiliom** [comment]
Ok, thanks. Good luck catching up!

**Comment by emiliom** [comment]
@ocefpaf any progress??

**Comment by ocefpaf** [comment]
No. I'm having 'fun' getting my new laptop properly configured. The old
system76 died.

**Comment by ocefpaf** [comment]
Emilio are you in a tight schedule for a new release? If so I recommend to
release more often, we can do one now and another one as soon as I update
the CLI tool.

**Comment by emiliom** [comment]
> Emilio are you in a tight schedule for a new release?

Not per se. I don't see any benefit from issuing a release now before the CLI tool is ready, so it's not worth the hassle. Hopefully next week?
