### ISSUE TITLE
Posgresql SSL issue when on production mode?

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#133]
I’m getting weird behavior for for postgresql, when running on a production setting. 

When I try to do Get Sites for the first time after the server is up, I am getting the expected output with a list of sites, etc. When I reload the page, I get this error:

```python
(psycopg2.OperationalError) server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. …
```
reload again I get
```python
(psycopg2.OperationalError) SSL error: decryption failed or bad record mac …
```
then lastly, another reload I get
```python
(sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back …
```
This does not happen with MySQL. And of course the error message is not helpful. I’ve tried running uwsgi like this: 
```bash
uwsgi --socket 0.0.0.0:8080 --protocol=http -w wsgi
```
It worked just fine, but when I make it live, it didn’t seem to work.

---

Currently one solution is to use `lazy` and `lazy-apps` option within uwsgi `ini` file.

```ini
lazy=true
lazy-apps=true
```

From [uWSGI Documentation](http://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html):

uWSGI tries to (ab)use the Copy On Write semantics of the [fork()](http://en.wikipedia.org/wiki/Fork_%28operating_system%29) call whenever possible. By default it will fork after having loaded your applications to share as much of their memory as possible. If this behavior is undesirable for some reason, use the `lazy-apps` option. This will instruct uWSGI to load the applications after each worker’s `fork()`. Beware as there is an older options named `lazy` that is way more invasive and highly discouraged (it is still here only for backward compatibility)

**Comment by lsetiawan** [comment]
After further research, it seems like `lazy-apps` option for uwsgi isn't necessary bad. `lazy` option is the one that's not good. 

By default `uwsgi` will use the `preforking` mode:

> By default uWSGI loads the whole application in the first process and after the app is loaded it does fork() itself multiple times. This is the common Unix pattern, it may highly reduce the memory usage of your app, allows lot of funny tricks and on some languages may bring you a lot of headaches.

`lazy-apps` mode:

> lazy-apps mode instead loads your application one time per worker. It will require about O(n) time to load it (where n is the number of workers), will very probably consume more memory, but will run in a more consistent and clean environment.

This is actually a good option for the app, though it will consume more memory, which isn't a big deal atm. This suggestions comes from http://uwsgi-docs.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html

Originally I thought that the SSL errors was caused by insecure connection (Using `http` instead of `https`, This actually didn't matter since I still got the same errors after configuring `nginx` to use `https`. The fix was to use lazy-apps. 

ping @emiliom

**Comment by emiliom** [comment]
Woo-hoo! :man_dancing:

**Comment by sreeder** [comment]
@emiliom @lsetiawan I was just getting on here to tell you guys about this. I  was able to get your current code running on our postgres server, I just had to add the lazy-apps setting!

**Comment by lsetiawan** [comment]
@sreeder YAAAAAAYYYY!!!! THAT'S AWESOME!! 😸

**Comment by lsetiawan** [comment]
I am closing this issue. It seems like the problems has not creep up again.
