### ISSUE TITLE
ODM2 timeseries GetVariableInfo Response Checks and Mapping

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#152]
## GetVariableInfo Response Against LittleBear MySQL Database
[GetVariableInfo Xml](http://54.186.36.247:8080/mysqlodm2timeseries/rest/1_1/GetVariableInfo)

### One Variable Unknowns:
```xml
...
<variableCode default="true" vocabulary="mysqlodm2timeseries" variableID="14">USU14</variableCode>
<variableName>Temperature</variableName>
<valueType>Unknown</valueType>
<dataType>Unknown</dataType>
<generalCategory>Unknown</generalCategory>
<sampleMedium>Air</sampleMedium>
...
```

- `dataType` : This attribute is being used currently, and it is pulled from ODM2 `Variables `[`VariableTypeCV`](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L28). 
    - [core_1_1.py#L828](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L828) will always result in `Unknown` unless the `VariableTypeCV` value matches a value in the list on [core_1_1.py#L903](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L903).

- `generalCategory` : This attribute is currently commented out in [sqlalch_odm2_models.py#L48](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L48) .
     -  [core_1_1.py#L830)](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L830) will result in `generalCategory` being `Unknown` always. See [core_1_1.py#L1002](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L1002)

- `valueType` : This attribute is currently commented out in [sqlalch_odm2_models.py#L43](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L43), which means that it's always be `None`. 
    - [core_1_1.py#L831](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L831) will result in `valueType` being 'Unknown' always. See [core_1_1.py#L1020](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L1020.)

- `sampleMedium` : This attribute is currently shown having a value, but sometimes the result is `Unknown`. It is currently being used, and it is pulled from ODM2 `Results` [`SampledMediumCV`](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L165).
    - [core_1_1.py#L829](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L829) would result in `Unknown` unless the `SampleMediumCV` value matches a value in the list on [core_1_1.py#L969](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L969).

**Comment by lsetiawan** [comment]
[WOF 1.1 Documentation](http://his.cuahsi.org/documents/WaterML_1_1_part1_v2.pdf)

Example from Documentation Pg. 72:
```xml
<variable>
 <variableCode vocabulary="LBR" default="true"
variableID="3">USU3</variableCode>
 <variableName>Battery voltage</variableName>
 <valueType>Field Observation</valueType>
 <dataType>Minimum</dataType>
 <generalCategory>Instrumentation</generalCategory>
 <sampleMedium>Other</sampleMedium>
 <unit>
 <unitName>volts</unitName>
 <unitType>Potential Difference</unitType>
 <unitAbbreviation>V</unitAbbreviation>
 <unitCode>168</unitCode>
 </unit>
 <noDataValue>-9999</noDataValue>
 <timeScale isRegular="true">
 <unit>
 <unitName>minute</unitName>
 <unitType>Time</unitType>
 <unitAbbreviation>min</unitAbbreviation>
 <unitCode>102</unitCode>
 </unit>
 <timeSupport>30</timeSupport>
 </timeScale>
 <speciation>Not Applicable</speciation>
 </variable>
```

From the example, it seem like:
- `dataType` (A3 pg. 89) should come from ODM2 `TimeSeriesResults` [`AggregationStatisticCV`](http://vocabulary.odm2.org/aggregationstatistic/).
- `generalCategory` (A4 pg. 90) should come from ODM2 `Variables` [`VariableTypeCV`](http://vocabulary.odm2.org/variabletype/).
- `valueType` (A10 pg. 95) should come from ODM2 `Actions` [`ActionTypeCV`](http://vocabulary.odm2.org/actiontype/) though the vocabulary doesn't match up exactly.

**Comment by horsburgh** [comment]
@lsetiawan - valueType is interesting. You're right, there's not a 1:1 match with ODM2. I can see that using the ActionTypeCV might work, but I could also see a case for using ResultType. I think your suggestion for using the ActionTypeCV for the valueType attribute seems reasonable.

**Comment by emiliom** [comment]
Thanks, @lsetiawan, and thanks for chiming in, @horsburgh! @lsetiawan, very nice use of links to documents, code and vocabularies :+1: 

I'm not adding any comments per se, yet. Just wanted to point to pre-generated WOFpy `GetVariableInfo` responses from our three current ODM2 timeseries test databases (LBR, EnviroDIY and Miguel's LCZO). I've [uploaded these WaterML1.1 XML files here](https://github.com/BiG-CZ/BiG-CZ-Toolbox/tree/master/tests) for further testing and assessments. It's a lot easier to deal with pre-generated files than live requests every time, which can be slow, or the service can be down.

I'll comment hopefully by Monday.

**Comment by emiliom** [comment]
@lsetiawan, thanks also for remembering to add this to issue to the [milestone](https://github.com/ODM2/WOFpy/milestone/3) we set up!

cc'ing @steveskrip

**Comment by lsetiawan** [comment]
@emiliom Thanks uploading those XML files. This is great to link to. 😃

**Comment by emiliom** [comment]
> `generalCategory` (A4 pg. 90) should come from ODM2 Variables [VariableTypeCV](http://vocabulary.odm2.org/variabletype/)

I agree that that's the best match. But it's also a very imperfect match, b/c ODM2 introduced concepts there that are not mapped to the WaterML 1.1 `generalCategory` concepts. Still, this is indeed the way to go as a first enhancement to `generalCategory` handling.

**Comment by emiliom** [comment]
More broadly, I think we'll have no choice but to create mappings between ODM2 CV's and these 4 WaterML 1.1 CV's. Some of these mappings will be imperfect, b/c of the conceptual mismatch. If we simply pass the ODM2 CV values, we'll be returning non-compliant WaterML 1.1 (though maybe I should re-read the WaterML 1.1 doc). 

Those mappings would also be customizable by WOFpy users, to provide flexibility.

**Comment by emiliom** [comment]
The 4 WaterML 1.1 CV's discussed each has a small list of terms (see the WaterML / WOF 1.1 document link in one of the comments above). So, I'm listing them here for convenient reference (would be nice to also add a link to the WaterML 1.1 CV online system, but I can't remember the url):

`dataType` (A3)
- Continuous
- Sporadic
- Cumulative
- Incremental
- Average
- Maximum
- Minimum
- Constant Over Interval
- Categorical

`generalCategory` (A4)
- Water Quality
- Climate
- Hydrology
- Biota
- Geology

`valueType` (A10)
- Field Observation
- Sample
- Model Simulation Result
- Derived Value

`sampleMedium` (A6)
- Surface Water
- Ground Water
- Sediment
- Soil
- Air
- Tissue
- Precipitation

**Comment by emiliom** [comment]
The term lists I posted immediately above are from the [WaterML 1.1 Manual (pdf)](http://his.cuahsi.org/documents/WaterML_1_1_part1_v2.pdf). But this manual was last edited in mid 2009, and in the meantime the WaterML 1.1 vocabularies continued to evolve, as represented in the live vocabulary system, ["Master Controlled Vocabulary Registry for ODM 1.1"](http://his.cuahsi.org/mastercvreg/cv11.aspx); for example, [generalCategory](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=GeneralCategoryCV&id=805577908) currently has double the number of terms as the 2009 manual (10 vs 5), and [valueType](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=ValueTypeCV&id=1141579105) now has 7 terms vs 4 in the manual!

*WOFpy should use the Master CV Registry or at least a recent/updated snapshot.*

**Comment by lsetiawan** [comment]
@emiliom Thanks for leading me to the Master CV Registry! Btw. I'll be working tonight for a few hours (probably until 9). I am looking at the CV for Water ML 1.1. Thinking maybe parsing the page to get the CVs

**Comment by emiliom** [comment]
> Thanks for leading me to the Master CV Registry!

Well, they were notes for me, too.

>  I'll be working tonight for a few hours (probably until 9). I am looking at the CV for Water ML 1.1. 

Alright.

**Comment by lsetiawan** [comment]
@emiliom Do you think that this WSDL will work with ulmo? http://his.cuahsi.org/odmcv_1_1/odmcv_1_1.asmx?WSDL

**Comment by horsburgh** [comment]
@emiliom and @lsetiawan - when I was running the Master CV registry for ODM 1.1.1 (before it moved to CUAHSI) I created that simple web service that would return the CV terms serialized as XML. You could probably use Python and suds to access it. It's super simple (but uses SOAP - sorry, it was in vogue back then...).

**Comment by emiliom** [comment]
> Do you think that this WSDL will work with ulmo? http://his.cuahsi.org/odmcv_1_1/odmcv_1_1.asmx?WSDL

It won't. It's not for a WaterML request, but instead for a vocabulary request.

Thanks @horsburgh! I was going to say roughly what you're saying. That Master CV service seems to return a fairly straightforward XML response that can probably be parsed easily after issuing the request with `suds`. But @lsetiawan hasn't used suds directly ...

**Comment by lsetiawan** [comment]
> It won't. It's not for a WaterML request, but instead for a vocabulary request.

@emiliom Thanks! I will try with `suds`.

**Comment by lsetiawan** [comment]
@horsburgh, @emiliom,

Thanks for the suggestions! `suds` works great. I was able to do the request and get the CV terms and definitions with no problem 😄 at least for `DataTypeCV` and `CensorCodeCV` so far.

**Comment by lsetiawan** [comment]
## ODM2 --> WaterML 1.1 CV Mapping

I am currently using the mapping in https://github.com/ODM2/WOFpy/issues/152#issuecomment-313770769. Here's a `waterml:odm2` cv table mapping dictionary. Another resource I found is [here](https://github.com/ODM2/ODM2/blob/master/usecases/WOF_to_ODM2/load_wof_to_ODM2.py).

```python
wmlodm2_cvmap = {
    'datatype' : 'aggregationstatistic',
    'unitstype' : 'unitstype',
    'samplemedium' : 'medium',
    'generalcategory' : 'variabletype',
    'valuetype' : 'actiontype',
    'censorcode' : 'censorcode'
}
```

Here's an inventory of ODM2 CV that doesn't currently match WaterML 1.1 CVs:

```python
medium
Number of ODM2CV: 19
Number of ODM2CV not mathing with WaterML 1.1: 12
[u'Vegetation', u'Rock', u'Regolith', u'Particulate', u'Organism', u'Not applicable', u'Mineral', u'Liquid organic', u'Liquid aqueous', u'Ice', u'Habitat', u'Gas']
_____________________________________________

aggregationstatistic
Number of ODM2CV: 18
Number of ODM2CV not mathing with WaterML 1.1: 6
[u'Standard error of the mean', u'Standard error of mean', u'Standard deviation', u'Constant over interval', u'Confidence Interval', u'Best easy systematic estimator']
_____________________________________________

actiontype
Number of ODM2CV: 23
Number of ODM2CV not mathing with WaterML 1.1: 23
[u'Cruise', u'Data retrieval', u'Derivation', u'Equipment deployment', u'Equipment maintenance', u'Equipment programming', u'Equipment retrieval', u'Estimation', u'Expedition', u'Field activity', u'Generic non-observation', u'Instrument calibration', u'Instrument deployment', u'Instrument retrieval', u'Observation', u'Simulation', u'Site visit', u'Specimen analysis', u'Specimen collection', u'Specimen fractionation', u'Specimen preparation', u'Specimen preservation', u'Submersible launch']
_____________________________________________

censorcode
Number of ODM2CV: 6
Number of ODM2CV not mathing with WaterML 1.1: 6
[u'Unknown', u'Present but not quantified', u'Not censored', u'Non-detect', u'Less than', u'Greater than']
_____________________________________________

unitstype
Number of ODM2CV: 179
Number of ODM2CV not mathing with WaterML 1.1: 161
[u'Absorbed dose', u'Absorbed dose rate', u'Amount of Information', u'Angular acceleration', u'Angular mass', u'Angular momentum', u'Angular velocity or frequency', u'Area angle', u'Area per length', u'Area temperature', u'Area thermal expansion', u'Area time', u'Area time temperature', u'Biological activity', u'Catalytic activity', u'Concentration count per count', u'Concentration count per mass', u'Concentration count per volume', u'Concentration or density mass per volume', u'Concentration percent saturation', u'Concentration volume per volume', u'Count', u'Count per area', u'Count per length', u'Currency', u'Data rate', u'Diffusivity', u'Dose equivalent', u'Dynamic viscosity', u'Electrical capacitance', u'Electrical charge', u'Electrical charge line density', u'Electrical charge per count', u'Electrical charge per mass', u'Electrical charge volume density', u'Electrical conductance', u'Electrical conductivity', u'Electrical current', u'Electrical current density', u'Electrical current per angle', u'Electrical current per energy', u'Electrical dipole moment', u'Electrical field strength', u'Electrical flux', u'Electrical flux density', u'Electrical permittivity', u'Electrical quadrupole moment', u'Electrical resistance', u'Electrical resistivity', u'Electromotive force', u'Energy density', u'Energy flux', u'Energy per area', u'Energy per area electrical charge', u'Energy per square magnetic flux density', u'Fluid permeance', u'Fluid resistance', u'Fluidity', u'Force per length', u'Gravitational attraction', u'Heat capacity', u'Heat transfer Coefficient', u'Hyperpolarizability', u'Inductance', u'Inverse count', u'Inverse energy', u'Inverse length', u'Inverse length temperature', u'Inverse magnetic flux', u'Inverse permittivity', u'Inverse square energy', u'Inverse time temperature', u'Inverse volume', u'Jerk', u'Length energy', u'Length fraction', u'Length integrated mass concentration', u'Length mass', u'Length molar energy', u'Length per magnetic flux', u'Length temperature', u'Length temperature time', u'Level', u'Linear acceleration', u'Linear energy transfer', u'Linear momentum', u'Linear thermal expansion', u'Linear velocity', u'Luminance', u'Luminous efficacy', u'Luminous Energy', u'Luminous flux', u'Luminous intensity', u'Magnetic dipole moment', u'Magnetic field strength', u'Magnetic flux', u'Magnetic flux density', u'Magnetic flux per length', u'Magnetic permeability', u'Magnetomotive force', u'Mass count', u'Mass count temperature', u'Mass flux', u'Mass fraction', u'Mass normalized particle loading', u'Mass per area', u'Mass per electrical charge', u'Mass per length', u'Mass per time', u'Mass temperature', u'Molar angular momentum', u'Molar conductivity', u'Molar energy', u'Molar heat capacity', u'Molar mass', u'Molar volume', u'Other', u'Particle flux', u'Particle loading', u'pH', u'Polarizability', u'Potential vorticity', u'Power area', u'Power area per solid angle', u'Power per area', u'Power per area quartic temperature', u'Power per electrical charge', u'Pressure or stress', u'Pressure or stress rate', u'Quartic electrical dipole moment per cubic energy', u'Radiance', u'Radiant Intensity', u'Radioactivity per volume', u'Satellite resolution', u'Snap', u'Solid angle', u'Specific energy', u'Specific heat capacity', u'Specific heat pressure', u'Specific heat volume', u'Specific radioactivity', u'Specific surface area', u'Specific volume', u'Stable isotope delta', u'Standard gravitational parameter', u'Temperature count', u'Temperature per magnetic flux density', u'Temperature per time', u'Thermal conductivity', u'Thermal insulance', u'Thermal resistance', u'Thermal resistivity', u'Thrust to mass ratio', u'Time squared', u'Torque', u'Volume thermal expansion', u'Volumetric flow rate', u'Volumetric flux', u'Volumetric heat capacity', u'Volumetric productivity', u'Yank']
_____________________________________________

variabletype
Number of ODM2CV: 23
Number of ODM2CV not mathing with WaterML 1.1: 15
[u'Water quality', u'Volatile', u'Uranium series', u'Trace element', u'Stable isotopes', u'Speciation ratio', u'Rock mode', u'Ratio', u'Rare earth element', u'Radiogenic isotopes', u'Noble gas', u'Model data', u'Major oxide or element', u'End-Member', u'Age']
_____________________________________________
```

**Comment by emiliom** [comment]
Remaining discussions shifted to #160. New release is out, closing this issue.
