### ISSUE TITLE
What DB systems are officially supported by WOFpy?

### ISSUE THREAD

**Issue by sreeder** [ODM2/WOFpy#157]
I am trying to run this on a MSSQL server and I was wondering if you guys had completed any testing against this database type?

I am receiving an error when I run the code. It is similar to an issue we were getting when we started running against PostgreSql
<img width="1120" alt="screen shot 2017-07-13 at 10 16 22 am" src="https://user-images.githubusercontent.com/4721940/28176390-69b8bf8c-67b4-11e7-8d0a-888e83c98308.png">

**Comment by lsetiawan** [comment]
We do not support MSSQL as of now. We have no way of testing and developing with that DB system. Currently, we are "officially" supporting MySQL, SQLite, and PostgreSQL.

**Comment by emiliom** [comment]
Just to add to what @lsetiawan said: we are not able to do any testing or development on MSSQL. So, to the extent that `odm2api` works with MSSQL (and to the extent that odm2api actually used in wofpy), and that the explicit SQL statements in the `wofpy` [odm2timeseries DAO](https://github.com/ODM2/WOFpy/tree/master/wof/examples/flask/odm2/timeseries) work with MSSQL (which we can't test), things "should" work with MSSQL ...

Maybe worth discussing this at next week's BiGCZ call.

**Comment by horsburgh** [comment]
Hi guys - I feel like we've done a MASSIVE amount of work over the past several years to make sure that the tools we are building for ODM2 are platform and database agnostic. I think it would be a real shame if this tool locked us into a particular way of doing things. There has always been a free version of SQL Server, and Windows is pretty easy to get your hands on.

That said - according to Stephanie, this error may have nothing to do with the fact that we are trying to use SQL Server as it is similar to other errors that have popped up when running with PostgreSQL.   Any chance you could look at this error more closely with @sreeder ?

**Comment by lsetiawan** [comment]
Hi @sreeder Could you please go through your dao, and try adding an `or` on the lines where it checks for the engine as 'postgresql'.

```python
if self.engine.name is 'postgresql' or self.engine.name is 'mssql':
```

https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L131, https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L142

See if that changes anything. Thanks.

**Comment by sreeder** [comment]
@lsetiawan I was able to add those changes last Friday, but have since been getting another error that I am unsure how to fix. I this something you have come across before?
![image](https://user-images.githubusercontent.com/4721940/28279650-57742802-6ade-11e7-9bdc-4f5a968aaaa5.png)

**Comment by lsetiawan** [comment]
I think that pops up when you don't have `[WOF]` in the `.cfg` file. https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_config_timeseries.cfg#L1

**Comment by sreeder** [comment]
@lsetiawan  That is strange, because my .cfg file looks nearly identical to that one.

**Comment by sreeder** [comment]
@lsetiawan  Okay, I was running the code from another folder, so it seems to have difficulty finding the path unless you run it from the same folder as the runserver.py file.

**Comment by lsetiawan** [comment]
@sreeder Hmm.. interesting. If the `.cfg` files are in a different folder. You should be able to make an absolute path. See below.

```python
M_CONFIG_FILE = os.path.join('/home/ubuntu', 'wofpy_prod', 'odm2_config_mysql.cfg')
```

**Comment by sreeder** [comment]
@lsetiawan Thanks for your help, I was able to get this up and running! So with your code fix from above

```python
if self.engine.name is 'postgresql' or self.engine.name is 'mssql':
```

https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L131, https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py#L142

I was able to get the code running against an MSSQL database.

**Comment by emiliom** [comment]
@sreeder, I'm really glad you made it work! Thanks so much for these detailed wrap-up comments and the additional set of instructions you've said you'll post as well. We'll want to capture the MSSQL-specific instructions in the general instructions for WOFpy.

It's instructive (for those of us who don't use MSSQL) to see that MSSQL SQL dialect is more similar to PostgreSQL than to MySQL. That's effectively what the code change you implemented from Don does:
```python
if self.engine.name is 'postgresql' or self.engine.name is 'mssql':
```

@lsetiawan, please make this change/update on master (submit PR) when you get a chance.

BTW, I'll rename this issue to something that refers to MS SQL specifically in the title, to make it easier to locate in the future.
