### ISSUE TITLE
Extract correct datetime range from Measurement Results, across specimens

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#16]
@cdesyoun, in [your implementation of querying "measurement result values with related features if there are no data values when querying measurement result value with sampling feature like time series data"](8#issuecomment-147007786), there's a problem with the datetime range (start and end) you're extracting. The start and end datetimes are always identical. It looks to me like you're taking the datetimes associated with only one of the `Specimen` `SamplingFeatures`, not across ALL `Specimen` `SamplingFeatures` related to the `Site` `SamplingFeature`.

You can see this problem with [the *march* site in my Marchantaria use case, in the seriesCatalog element in GetSiteInfo requests](http://sis-devel.cloudapp.net:8080/GetSiteInfo?site=ODM2WofPy:march).

[See my comments and sample PostgreSQL SQL code in Issue 15](15#issuecomment-147314744), for an example of proper calculation of cross-specimen datetime ranges.

**Comment by cdesyoun** [comment]
Emilio, it is very useful to understand the marchantaria time series data for the implementation.
I think I fixed it on my development.
