### ISSUE TITLE
Add agencyName and agencyCode in SiteInfo response

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#162]
From *John McEnery*. His original question:
> Does the organizationname and organizationcode in odm2 correspond to `agencyName` and `agencyCode` in WaterML 1.1?

Followed by more detailed information:
> These links are a few of the places where Lauren and I had found reference to agencyCode and agencyName for WaterML 1.1.  It appears to be an element of SiteInfo.  The first 2 links are from CUAHSI, the later links are use examples from USGS and EPA.
> - http://his.cuahsi.org/documents/cuahsiTimeSeries_v1_1.xsd
> - http://his.cuahsi.org/documents/WaterML_1_1_part3_v2.pdf
> - https://help.waterdata.usgs.gov/codes-and-parameters/codes#agency_cd
> - https://help.waterdata.usgs.gov/code/agency_cd_query?fmt=html
> - https://hisprod.rtnccad.epa.gov/prod/CUAHSI_1_1.asmx?op=GetSiteInfoObject 

*And my initial comments (sent before he sent those detailed references):*
I looked at the official WaterML 1.1 documentation and sample XML files (sorry, I don't have the url handy right now, but it's on the CUAHSI web site); I couldn't find any reference to agencyName and agencyCode XML elements.

What's there, in the "source" element of a `GetValues` response, is `organization`, `sourceDescription`, `sourceCode` and the `sourceID` attribute of the `source` element. The mappings to the ODM2 timeseries in WOFpy are:

**WaterML1.1 : ODM2**
organization : OrganizationName
sourceDescription : OrganizationDescription
sourceID attribute : OrganizationID

We seem to be missing `sourceCode` in our wofpy WaterML 1.1 response, but in all cases I've seen in the documentation, it's identical to the `sourceID` attribute. And actually, the WaterML 1.1 documentation never defines its meaning; examples are provided, but it's never discussed (at least based on a text search on "sourcecode" on the pdf manual). We should add it to WOFpy for completeness, but its recommended usage doesn't seem to be the equivalent of ODM2's `OrganizationCode`.

**DON:** It looks to me like this assignment is wrong and never actually used:
https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L207
`self.OrganizationCode = aff_obj.OrganizationObj.OrganizationCode`
It should be replaced with:
`self.SourceCode = aff_obj.AffiliationID`

From what I've seen, once we fix that, the XML `sourceCode` element will be generated. But it'll still be the same as "sourceID", not the string used in ODM2 `OrganizationCode`.

**Comment by emiliom** [comment]
For reference: See comment in `create_site_info_element` about missing `agencyName`
at [wof/core_1_1.py#L726](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L726)

**Comment by emiliom** [comment]
*My comments addressed to John (mainly), copied from email follow-up, but edited a bit to make references to this github issue less obtrusive:*

Thanks so much for the detailed information; that's really helpful. I definitely see `agencyCode` and `agencyName` mentioned or used in these resources.

I'm cc'ing Jeff (though I think he's on vacation this week) b/c I don't see a definition of what an "agency" is, so his CUAHSI HIS institutional memory would be helpful here. Typically an agency is government associated; but the USGS listing you mentioned,
https://help.waterdata.usgs.gov/code/agency_cd_query?fmt=html
includes universities as agencies. However, I don't think that page is a WaterML resource. It looks more like a resource about USGS internal codings.

So, in the absence of clear definitions in the WaterML 1.1 documents, my hunch (until we get input from Jeff) is that agencyCode and agencyName in WaterML 1.1 are intended to be used by government agencies, which means that a government user of WOFpy should tweak the code to use them, whereas a university user would not use them. They're not used in any of the WaterML examples derived from Jeff's work or Utah State University.

Still, more fundamentally, WOFpy first needs to provide the machinery so a user can map to those attributes. It looks like the machinery isn't there. I've opened this github issue to help us make progress on this.

@lsetiawan, please start looking into this.

**Comment by lsetiawan** [comment]
@emiliom,

> WaterML1.1 : ODM2
organization : OrganizationName
sourceDescription : OrganizationDescription
sourceID attribute : OrganizationID

It seems like SourceID is actually mapped to `AffiliationID` rather than `OrganizationID` ([sqlalch_odm2_models.py/L203](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L203)). Is `OrganizationID` supposed to be the correct mapping? Thanks.

**Comment by emiliom** [comment]
> It seems like SourceID is actually mapped to AffiliationID rather than OrganizationID (sqlalch_odm2_models.py/L203). Is OrganizationID supposed to be the correct mapping?

Good catch. Conceptually I think we want OrganizationID, but we'll need to look more closely at the code to see if there are any side effects.

**Comment by emiliom** [comment]
> Conceptually I think we want OrganizationID, but we'll need to look more closely at the code to see if there are any side effects.

For the record, we're *de facto* retaining the use of `AffiliationID` for `SourceID`, at least for now (eg, in [this merged commit](https://github.com/ODM2/WOFpy/pull/164/commits/230530f88a41ef468ab911d3a298a64a6419ea0b)).

**Comment by emiliom** [comment]
An additional comment about the implementation: `agencyName` and `agencyCode` have been set to be exposed only if `OrganizationTypeCV in ['Government agency', 'Research agency']`. Of course, a wofpy user is free to tweak the ODM2 timeseries DAO code to override that setting.

**Comment by emiliom** [comment]
Fixed by #163 and #164. Closing
