### ISSUE TITLE
Prepare for new release, v2.2.0 (no beta)

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#166]
Previous release out on June 14: https://github.com/ODM2/WOFpy/releases/tag/v2.1.0b0. Also [refer to current Milestone](https://github.com/ODM2/WOFpy/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Test+WOFpy+responses+against+ODM2+databases%22)

Distinguish between bug fixes involving **failures** vs ones involves inappropriate or mishandled **response content**.

A list of **enhancements** and **bug fixes**, in no particular order at this time:

- Add `agencyName` and `agencyCode` in `GetSiteInfo` response (#162, #164)
- Added missing `Source` and other elements from ODM2 timeseries DAO in `GetSiteInfo` (#163)
- Added missing `SourceCode` attribute in `GetValues` (#163)
- In `GetSiteInfo` 1.1 response, fixed mixed, incorrect use of `note` element (instead of `siteProperty`) and added exemption handling for cases where ODM2 `SamplingFeatures.SamplingFeatureDescription` and other relevant attributes are empty (#168, #171)
- Added `GetVariables` sample request to sample REST web page (#169)
- Improved unicode support; fixed failures when unicode characters were encountered (#148, #155, #158)
- Generalized handling of errors in database interactions (#170, #172, #173)
- Much better handling of some CV's (specially for `GetVariableInfo`), including mappings from ODM2 to WaterML 1.1; includes new functionality to cache relevant WaterML 1.1 CV's (#160, #152, #153, #159, #175, #177, #178, #181, #182)
- MS SQL testing and fixes for ODM2 timeseries DAO (#157, #174). 

*Note: most testing focused on WOF/WaterML 1.1 only.*

**Comment by lsetiawan** [comment]
> includes new functionality to cache relevant WaterML 1.1 CV's (#160, #152)

Maybe this should also be #153?

**Comment by emiliom** [comment]
> Maybe this should also be #153

Thanks. Please feel free to edit the comment directly! I've added your suggestion. Though I'm trying to focus on referencing issues, unless an item arose from a PR/commit and not directly from an issue (or wasn't directly discussed there).

**Comment by lsetiawan** [comment]
> Though I'm trying to focus on referencing issues, unless an item arose from a PR/commit and not directly from an issue (or wasn't directly discussed there).

Ah! Got it. Thanks.

**Comment by ocefpaf** [comment]
@lsetiawan please feel free to ping me in any PR you need a second pair of eyes.
Also, once we are done I can update the `conda` for `WOFPy`.

**Comment by lsetiawan** [comment]
> In GetSiteInfo 1.1 response (SOAP only?)

@emiliom what do you mean by SOAP only? this is in REST result. http://54.186.36.247:8080/mysqlodm2timeseries/rest/1_1/GetSiteInfo?site=mysqlodm2timeseries:USU-LBR-Mendon

**Comment by emiliom** [comment]
**Version number:** there will be so many bug fixes and enhancements in this release, let's just call it "2.2.0" (no beta, and 2.1 > 2.2)

**Comment by emiliom** [comment]
> @emiliom what do you mean by SOAP only? this is in REST result also

Thanks. I had a vague memory that it was limited to SOAP. I've edited the text.

**Comment by emiliom** [comment]
@ocefpaf, just a heads-up that @lsetiawan and I are wrapping up the last PR's (on #160) before we issue a new WOFpy release. Unless surprises come up, we'll be ready to stamp the new release by tonight (our tonight!). Please be ready to work with me Thursday and Friday to get a conda package ready by Friday! (FYI, @lsetiawan is unavailable on Thursday, the day of the week he works for a different PI)

**Comment by ocefpaf** [comment]
> Please be ready to work with me Thursday and Friday to get a conda package ready by Friday! 

Standing by and read to :shipit:

**Comment by emiliom** [comment]
### TO-DO's after this release (in no particular order):

- Add parsing and reporting of state from address string (#168)
- Add [MS SQL ODM2 DAO configuration instructions](157#issuecomment-316132393) to installation & config doc
- In `GetSiteInfo*` responses, `Variable` `TimeUnits` and `TimeSupport` are not populated, b/c they would involve querying `TimeSeriesResultValues`, which is not currently done in `get_series_by_sitecode` and `get_series_by_sitecode_and_varcode`
- `GetSites` has an empty `seriesCatalog` element. I don't remember if it's supposed to be there at all, or if it should be populated. But it's been like that for some time.
- Revisit the suite of tests (#180)

**Comment by emiliom** [comment]
@ocefpaf The new release [v2.2.0](https://github.com/ODM2/WOFpy/releases/tag/v2.2.0) is out. Package away!

**Comment by ocefpaf** [comment]
PyPI done: https://pypi.python.org/pypi/WOFpy/2.2.0

Conda next...

**Comment by emiliom** [comment]
Thanks @ocefpaf!

@lsetiawan: tomorrow, remember to update the public/live WOFpy endpoints on our AWS. First thing in the morning, assuming the conda package is ready.

**Comment by emiliom** [comment]
Looks like the conda packages for the 3 OS's are now ready: https://anaconda.org/odm2/wofpy/files

Thanks, @ocefpaf !

**Comment by ocefpaf** [comment]
Yep. All platforms are available now.

**Comment by emiliom** [comment]
Once @lsetiawan has updated our live sample WOFpy endpoints tomorrow morning, and then we've also updated (re-run) the [notebook that runs some tests](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpy_ODM2_SOAPandREST_Tests.ipynb) on both of the endpoints, we're done. I'll close this issue then.

Finally, I'll send a wider announcement tomorrow once those two tasks are completed.

Thanks again!!

**Comment by emiliom** [comment]
> Once @lsetiawan has updated our live sample WOFpy endpoints tomorrow morning, and then we've also updated (re-run) the notebook that runs some tests on both of the endpoints, we're done. I'll close this issue then.

Done, and the notebook tests are all passing. Closing this issue.
