### ISSUE TITLE
Overhaul/prettify default WOFpy test HTML pages

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#167]
The current WOFpy endpoint test HTML pages are ugly as sin. eg:
- http://54.186.36.247:8080/postgresqlodm2timeseries/
- http://54.186.36.247:8080/postgresqlodm2timeseries/rest_1_1/

We should discuss improvements to it, both to make them more user friendly and appealing, and to include useful information; for example, the version/release number of the WOFpy instance being used, and maybe contact and other information from the DAO configuration files (if easy to incorporate).

@lsetiawan, this is NOT an immediate priority, so don't get carried away yet :stuck_out_tongue_winking_eye: But I know you can whip up something nice looking fairly easily. Please add ideas and suggestions here before actually doing any work on this.

**Comment by lsetiawan** [comment]
## List of improvements

- [ ] Styling change should use [Bootstrap](https://getbootstrap.com/docs/3.3/)

**Comment by emiliom** [comment]
> Styling change should use Bootstrap

I'm cool as long as Bootstrap is *very* lightweight and doesn't introduce external js library dependencies that could break down the road.

**Comment by emiliom** [comment]
With PR #210 merged, the next thing will be to just finalize the text in the templates, including some links for that text. I'll work on that either late today or tomorrow.

**Comment by lsetiawan** [comment]
The changes made in #214 looks great! See it in http://54.186.36.247:8000/wofpypostgres/

**Comment by emiliom** [comment]
Thank you for deploying it!!! Yeah, it's looking terrific. Worth all the effort we put in, I think.

See #215 though (we both missed that!). Either one of us can take care of it. I won't do it in the next couple of hours.

**Comment by emiliom** [comment]
I've added  http://54.186.36.247:8000/wofpypostgres/ to the github issue listing our AWS resources.

I forgot to say: nice touch on the config info for that sample instance (APL-UW org, you as contact, etc)

**Comment by emiliom** [comment]
Also forgot to comment: the WOFpy version says "0", but I assume (from recent discussions) everything is set to have the correct version shown when installed from conda package?

**Comment by lsetiawan** [comment]
> the WOFpy version says "0", but I assume (from recent discussions) everything is set to have the correct version shown when installed from conda package?

Yepp. Ingore my versioning, that deployment is a development without git.

**Comment by emiliom** [comment]
Great, thanks.

**Comment by lsetiawan** [comment]
Once the release is out, I will update our "production" development servers. Thanks.

**Comment by emiliom** [comment]
Done! Closing.
