### ISSUE TITLE
WOF 1.1

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#2]
Add WaterOneFlow 1.1 and WaterML 1.1 as a soap interface.

Tasks (not necessarily in order) :
* add wof11_temp.wsdl to WOFpy/wof/flask/templates
* add/update rest and wsdl classes. Rest should update paths to 1_0 and 1_1
** /soap/wateroneflow_1_1.wsdl
* implement core objects with a 1.1 flavor
* add 1.1 features to the 1.0 model (or can we just add a 1.1 class that extends WOFpy/wof/models.py

**Comment by emiliom** [comment]
@cdesyoun and @valentinedwv, do you have a rough estimate when WOF 1.1 and WaterML 1.1 might be ready? No rush, just want to have some idea, to plan my testing. Thanks. Great to see all the progress!

**Comment by emiliom** [comment]
So, any rough idea of when WOF 1.1 and WaterML 1.1 might be ready?

**Comment by cdesyoun** [comment]
Emilio, I will try to release it tomorrow.

**Comment by emiliom** [comment]
Have you pushed all updates to the github repo? It doesn't look that way. The [commits history](https://github.com/ODM2/WOFpy/commits/master) shows only one commit, a week ago, since the repo was forked. ie, one commit since 2011.

**Comment by cdesyoun** [comment]
Emilio, I pushed all updates.

**Comment by emiliom** [comment]
Great, Thanks!

**Comment by valentinedwv** [comment]
Implemented.
