### ISSUE TITLE
Make Flask (index and wsdl) pages, spyne applications

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#20]
These pages should be made routes in a couple of 'application's, so that they can be used in other frameworks.

separate index, and wsdl "applications"
I hope that this will prep us add a swaggerui to the rest pages.

**Comment by valentinedwv** [comment]
I would use Jinja2 as the template engine to replace the templating in flask.

**Comment by cdesyoun** [comment]
David,

For considering to support swagger APIs for the restful services/flask apps, I think we need to look into two implementation sites.
https://github.com/rantav/flask-restful-swagger
https://github.com/gangverk/flask-swagger

**Comment by valentinedwv** [comment]
It's a fixed set of small rest interfaces
we can make a template like we do for wsdl's

**Comment by valentinedwv** [comment]
WSDL's can be found at  wateroneflow/.wsdl wateroneflow_1_1/.wsdl
