### ISSUE TITLE
Preparing for new release, 2.3.0

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#201]
We've made a couple of helpful bug fixes and error-trapping improvements since the last release (thanks largely to input from @miguelcleon, as well as an out-of-the-blue external contribution!). I'd like to push these into a new minor release (and conda package) fairly soon, well before the workshop. @lsetiawan will be on leave most of the week of October 24, so I'll shoot for a new release the following week.

@horsburgh & @aufdenkampe, have you made progress with your EnviroDIY WOFpy, with additional testing and such? If so, please let us know soon if you have questions or potential problems. That way we'll have a good chance of rolling into the new release any changes stemming from your feedback.

cc @aufdenkampe @horsburgh @ocefpaf

**Comment by horsburgh** [comment]
@emiliom - @jcaraballo17 is trying to deploy WOFPy on our new production server as part of the next release of data.envirodiy.org, but we haven't really done any additional tests or tweaks. Just need to get the latest/best version working for the Envirodiy release. @jcaraballo17 is trying to follow the steps that @sreeder left him before she went on leave, but if there are updated instructions/code that he should be using, please let us know.

**Comment by ocefpaf** [comment]
@emiliom I am back from my "leave" and with access to internet. As soon as you issue the new release I can prepare the PyPI and conda packages.

**Comment by emiliom** [comment]
Let's try to address #202 (missing `unit/unitCode`) in the next release.

**Comment by emiliom** [comment]
@horsburgh, thanks for the update. You should install only from the latest conda package, unless we give you very specific reasons not to (eg, we fix on master a bug you found, and we'd like you to test the fix). We aim not to let many improvements or bug fixes accumulate before issuing new releases and packages -- hence the preparation for this new minor release. I suspect that the issues we ran into (and addressed) with @miguelcleon's database won't impact EnviroDIY.

I haven't yet cleaned up / removed other installation documentation, but the document to use is still the one @lsetiawan and I pointed you and @sreeder to last time that question came up; that's [here](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBR_installation.md), and it's also unambiguously mentioned in the README file (edited after you pointed out to us that the guidance on the README was confusing :smile_cat: ). That installation document is fairly well battle tested by now.

**Comment by emiliom** [comment]
Other targets for the next release:
- Examine the current unicode character errors in the envirodiy WOFPY. From Jeff: "we are still getting some character encoding errors. For example, see: http://wpfwebstaging.uwrl.usu.edu/wofpy/rest/1_1/GetVariables". If we're lucky this is the same issue already addressed recently for Miguel's WOFpy (issue #148 and PR #197)
- See if we can add some flexibility to the current hard wiring (I think?) of `network name = vocabulary = url endpoint element`.

**Comment by emiliom** [comment]
@lsetiawan is working on #167, and making great progress! The new facelift for the landing page and REST endpoint sample pages will go on the new release.

**Comment by emiliom** [comment]
The new release is almost ready! And it's not so minor any more. So, I'll be bold and tag it as **2.3.0**

@ocefpaf: @lsetiawan and I will have a tagged release ready by tonight. So, hopefully tomorrow morning you can update the conda package (and PyPI? I forget if we're doing that).

**Comment by ocefpaf** [comment]
> So, I'll be bold and tag it as 2.3.0

:+1: 

> So, hopefully tomorrow morning you can update the conda package

Sure.

> and PyPI? I forget if we're doing that.

We are :smile:

**Comment by emiliom** [comment]
For reference for crafting the release notes, see https://github.com/ODM2/WOFpy/releases/tag/v2.2.0
(I'll draft the release notes within this issue)

**Comment by emiliom** [comment]
Add [MS SQL ODM2 DAO configuration instructions](157#issuecomment-316132393) to installation & config doc (Is it already done?)

**Comment by emiliom** [comment]
2.3.0 release is finally out! Closing this issue.
