### ISSUE TITLE
Missing unitCode element in WaterML 1.1 responses from ODM2 timeseries DAO

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#202]
Looks like WOFpy may not be including a `unit/unitCode` element in its WaterML 1.1 responses. It is including the `unit` attribute `unitID` for `timeScale/unit`, but that's apparently deprecated (according to 1.1 documentation, it's no longer required).

For `unitCode` we can just use the integer value currently inserted as `unitID`.

I validated sample WOFpy responses using the XML schema `cuahsitimeseries_v1_1.xsd` available at [this CUAHSI page](https://www.cuahsi.org/data-models/for-developers), downloadable as part of the file [WaterML1_1.zip](http://www.cuahsi.org/uploads/pages/img/WaterML1_1.zip).

**Note:** I should follow up with CUAHSI to ask that `cuahsitimeseries_v1_1.xsd` be loaded online (not just in a zip file), for direct XML schema validation.

**Comment by lsetiawan** [comment]
> I validated sample WOFpy responses using the XML schema cuahsitimeseries_v1_1.xsd 

What tool did you use to validate this? If it's some sort of python module, maybe we can add this to the test? Thanks.

**Comment by emiliom** [comment]
> What tool did you use to validate this? If it's some sort of python module, maybe we can add this to the test? 

OxygenXML. But I'm sure there are shell or python-based tools (eg, within `lxml`) that can do that. 

Don't bother with this issue today, though. I'll look into it this week.

**Comment by emiliom** [comment]
Fixed in PR #207.
