### ISSUE TITLE
fix unicode / special characters in "units" for ODM2 timeseries DAO

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#204]
See "mu" (micro) character in EnviroDIY endpoints (and ODM2 more broadly!).

- http://54.186.36.247:8000/postgresqlodm2timeseries/rest/1_1/GetVariables
- http://wpfwebstaging.uwrl.usu.edu/wofpy/rest/1_1/GetVariables

**Comment by emiliom** [comment]
Update ... it appears that this issue was actually already addressed in master, in one of the latest couple of commits! The WOFpy deployment at http://54.186.36.247:8000/postgresqlodm2timeseries/rest/1_1/GetVariables is probably old.

Once we've fully confirmed this we'll close this issue.

**Comment by emiliom** [comment]
It'll be good to refer to this issue explicitly in the release notes, though, to make it clear that handling of units special characters is a bug fix included in the upcoming new release.

**Comment by lsetiawan** [comment]
> Once we've fully confirmed this we'll close this issue.

I have updated the WOFpy development deployment that uses current master, and sure enough the Unicode problem is gone. Thanks.

**Comment by emiliom** [comment]
Woo-hoo!

**Comment by emiliom** [comment]
Taken care of by a previous PR. Closing.
