### ISSUE TITLE
In value elements, align each attribute code with corresponding metadata element id/code

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#209]
Ensure that the metadata reference attributes in each `<value>` element of the `GetValues` WaterML 1.1 response align unambiguously with the corresponding metadata elements.

Sample `<value>` element with metadata reference attributes `censorCode`, `methodCode`, `sourceCode` and `labSampleCode`:
```xml
<value 
 censorCode="nc" methodCode="25" sourceCode="3" labSampleCode="93" qualityControlLevelCode="2"
 dateTime="2007-11-13T12:30:00" timeOffset="-07:00" dateTimeUTC="2007-11-13T19:30:00">
  2.5
</value>
```

**Comment by emiliom** [comment]
@lsetiawan if you can take care of this today, we (or you) will be done with WOFpy today! We turn it over to Filipe for packaging, after I tag the release. Thanks!!

**Comment by lsetiawan** [comment]
> @lsetiawan if you can take care of this today, we (or you) will be done with WOFpy today! We turn it over to Filipe for packaging, after I tag the release. Thanks!!

Working on it now as we speak, thanks.

**Comment by emiliom** [comment]
Awesome!! Taken care of (PR #211). Closing now.
