### ISSUE TITLE
No WaterML 2 output in wof_spyne branch

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#21]
Add route on it's own class for now.
Use a Jinja2 template to produce the output.

**Comment by cdesyoun** [comment]
David, I think you added it already below.

app.add_url_rule(servicesPath+'/rest/1_0/GetValuesWML2', 'get_values_wml2', get_values_wml2)
app.add_url_rule(servicesPath+'/rest/1_1/GetValuesWML2', 'get_values_wml2_1_1', get_values_wml2_1_1)
