### ISSUE TITLE
Add dropped "GetValues request may kill your server" text in REST HTML templates

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#215]
Just realized that we forgot to retain the useful warnings in the REST HTML templates about GetValues requests that may be too big and can kill the server :)

Let's fix that today before issuing the release. 

ref #167

**Comment by lsetiawan** [comment]
I didn't leave it out. If you hover over the url you'll see it 😜

**Comment by emiliom** [comment]
You're good!!! I like it. Closing the issue, then.

**Comment by lsetiawan** [comment]
Thanks! Yea, I didn't like the clutter it made. 😄
