### ISSUE TITLE
CUAHSI CV 1.1 web service is down, impacts ODM2 timeseries DAO

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#239]
See PR #238 

And the [Travis-CI errors.](https://travis-ci.org/ODM2/WOFpy/jobs/567483096#L1691)

**Comment by martinseul** [comment]
Hi Emilio, 
am i understanding correctly that you have problems with the cv hosted here http://his.cuahsi.org/mastercvreg/cv11.aspx . I did move the hosting to a different machine to consolidate our infrastructure and thought all was working well... I did check again and had to change one additional setting. Would you please conform if all is working correctly for you now. 

Sorry for the inconvenience
Martin

**Comment by emiliom** [comment]
Hi Martin. Wow, I'm really impressed that you found this github issue that I created just 48 hours ago! It was more of a reminder to me to follow up later. Thanks so much for taking the time to follow up.

The SOAP CV service we've been using has this WSDL end point: http://his.cuahsi.org/odmcv_1_1/odmcv_1_1.asmx?WSDL. Except for the `?WSDL` parameter, that's the url still listed at http://his.cuahsi.org/mastercvreg/cv11.aspx, under "Updating your controlled vocabularies". It's returning an error. http://his.cuahsi.org/odmcv_1_1/odmcv_1_1.asmx and http://his.cuahsi.org/odmcv_1_1/odmcv_1_1.asmx?WSDL return the same error.

Thanks again.

**Comment by martinseul** [comment]
Hi Emilio,

I was working on the migration last week so I picked this one up. I think I did find the problem and fixed it. Please check and let me know if the problem persists.

Thanks
Martin

**Comment by emiliom** [comment]
It works now. Thanks so much, Martin!
