### ISSUE TITLE
WOF11 GetSiteInfoMultiple not working

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#25]
At least on the soap side:
```
<soap11env:Envelope xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/">
   <soap11env:Body>
      <soap11env:Fault>
         <faultcode>soap11env:Client.SchemaValidationError</faultcode>
         <faultstring>:4:0:ERROR:SCHEMASV:SCHEMAV_CVC_ELT_1: Element '{http://www.cuahsi.org/his/1.1/ws/}GetSiteInfoMultpleObject': No matching global declaration available for the validation root.</faultstring>
         <faultactor/>
      </soap11env:Fault>
   </soap11env:Body>
</soap11env:Envelope>
```

**Comment by cdesyoun** [comment]
SOAP URL: http://sis-devel.cloudapp.net:8080/ODM2Timeseries/soap/wateroneflow_1_1/
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://www.cuahsi.org/his/1.1/ws/">
   <soapenv:Header/>
   <soapenv:Body>
      <ws:GetSiteInfoMultipleObject>
      <!--Optional:-->
         <ws:site>
            <!--Zero or more repetitions:-->
            <ws:string>LR_TWDEF_C</ws:string>
         </ws:site>
         <!--Optional:-->
         <ws:authToken>?</ws:authToken>
      </ws:GetSiteInfoMultipleObject>
   </soapenv:Body>
</soapenv:Envelope>
```
SOAP URL: http://sis-devel.cloudapp.net:8080/ODM2Measurement/soap/wateroneflow_1_1/
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://www.cuahsi.org/his/1.1/ws/">
   <soapenv:Header/>
   <soapenv:Body>
      <ws:GetSiteInfoMultipleObject>
      <!--Optional:-->
         <ws:site>
            <!--Zero or more repetitions:-->
            <ws:string>march</ws:string>
         </ws:site>
         <!--Optional:-->
         <ws:authToken>?</ws:authToken>
      </ws:GetSiteInfoMultipleObject>
   </soapenv:Body>
</soapenv:Envelope>
```
When testing the above them, it worked fine.
I don't know why you have this.

**Comment by valentinedwv** [comment]
Sting should be
Network:sitecode

**Comment by cdesyoun** [comment]
Either one is working, for example, in case of ODM2 measurement data use case, ODM2Measurement:march, or march.
But, if you use the different network name, it returns no data.

**Comment by valentinedwv** [comment]
Spelling error that's embedded in interface. oops.
GetSiteInfoMultpleObject changed to GetSiteInfoMultipleObject

**Comment by cdesyoun** [comment]
David, I noticed it before so that I fixed it on the wsdl template.
In your WOF service on water.sdsc.edu, the misspelled "GetSiteInfoMultpleObject" is still being used.

**Comment by valentinedwv** [comment]
Yes, it's in there, been there for years... so it will have to stay, and be
misspelled in the WOFPY service, too

**Comment by cdesyoun** [comment]
I fixed it on wsdl_1_1_template.wsdl in WOFpy already.

**Comment by valentinedwv** [comment]
If it's misspelled in the WSDL on Water, it needs to be misspelled in the
WOFPY WSDL and code.
They  need to match.

**Comment by cdesyoun** [comment]
David, I did leave the misspelled "GetSiteInfoMultpleObject" on WSDL and code in WOFpy.
Again, I redeployed it on test sites below:

----------------------------------------------------------------
Acess HTML descriptions of endpoints at
http:// sis-devel.cloudapp.net:8080/ODM2Measurement/
http:// sis-devel.cloudapp.net:8080/ODM2Measurement/rest_1_0/
http:// sis-devel.cloudapp.net:8080/ODM2Measurement/rest_1_1/
http:// sis-devel.cloudapp.net:8080/ODM2Measurement/rest_2/
http:// sis-devel.cloudapp.net:8080/ODM2Measurement/soap/wateroneflow.wsdl
http:// sis-devel.cloudapp.net:8080/ODM2Measurement/soap/wateroneflow_1_1.wsdl
http:// sis-devel.cloudapp.net:8080/ODM2Timeseries/
http:// sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_1_0/
http:// sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_1_1/
http:// sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_2/
http:// sis-devel.cloudapp.net:8080/ODM2Timeseries/soap/wateroneflow.wsdl
http:// sis-devel.cloudapp.net:8080/ODM2Timeseries/soap/wateroneflow_1_1.wsdl
