### ISSUE TITLE
ODM2 Timeseries

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#26]
In the soap UI tests, I add two days to the start time of a series.
No data values are returned.
Is this a code error, or a database error

```
<soap11env:Envelope xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/">
   <soap11env:Body>
      <soap11env:Fault>
         <faultcode>soap11env:Server</faultcode>
         <faultstring>Values Not Found for LR_TWDEF_C:AirtTemp_Avg for dates 2015-04-28T00:00:00 - 2015-04-30</faultstring>
         <faultactor/>
      </soap11env:Fault>
   </soap11env:Body>
</soap11env:Envelope>
```

**Comment by cdesyoun** [comment]
I changed the code from 
```
if not valueResultArr:
            raise Exception("Values Not Found for %s:%s for dates %s - %s" % (
                siteCode, varCode, startDateTime, endDateTime))
```
to
```
if not valueResultArr:
      timeSeries = WaterML.TimeSeriesType()
       timeSeriesResponse.set_timeSeries(timeSeries)
       return timeSeriesResponse
```
Then if there is no data values, the result is as follows:
```
<soap11env:Envelope xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.cuahsi.org/his/1.0/ws/">
   <soap11env:Body>
      <tns:GetValuesObjectResponse>
         <timeSeriesResponse xmlns="http://www.cuahsi.org/waterML/1.0/">
            <queryInfo>
               <criteria>
                  <locationParam>LR_TWDEF_C</locationParam>
                  <variableParam>AirtTemp_Min</variableParam>
                  <timeParam>
                     <beginDateTime>2015-04-28T00:00:00</beginDateTime>
                     <endDateTime>2015-04-30T00:00:00</endDateTime>
                  </timeParam>
               </criteria>
               <note/>
               <extension/>
            </queryInfo>
            <timeSeries name="None"/>
         </timeSeriesResponse>
      </tns:GetValuesObjectResponse>
   </soap11env:Body>
</soap11env:Envelope>
```

**Comment by valentinedwv** [comment]
Message is fine. 

The question is that service says there is data from start to end.
But if I ask for the start plus a couple of days, i get no data values.

So, I assume this is an issue with the database having the incorrect start date.

Assigning to jeff to look into it.

**Comment by horsburgh** [comment]
@valentinedwv - Which database are you working from?

**Comment by cdesyoun** [comment]
Jeff, currently, I used this YODA file (https://github.com/ODM2/YODA-Tools/blob/master/jsonschema/examples/Timeseries_Template_Working_my_version.yaml), which you created. I loaded it into the postgreSQL server for testing the time series data. Do you have any public database connection which I can test for odm2 time series data (LBR)?

**Comment by cdesyoun** [comment]
David, I think this is the time range problem. this data is between 2010-06-03T11:15:00 and 2010-07-08T10:45:00. I tested the request below for two days.
It returned data values.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://www.cuahsi.org/his/1.0/ws/">
   <soapenv:Header/>
   <soapenv:Body>
      <ws:GetValuesObject>
         <!--Optional:-->
         <ws:location>LR_TWDEF_C</ws:location>
         <!--Optional:-->
         <ws:variable>AirtTemp_Min</ws:variable>
         <!--Optional:-->
         <ws:startDate>2010-06-03T11:15:00</ws:startDate>
         <!--Optional:-->
         <ws:endDate>2010-06-05T11:15:00</ws:endDate>
         <!--Optional:-->
         <ws:authToken>?</ws:authToken>
      </ws:GetValuesObject>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by horsburgh** [comment]
@cdesyoun - The Yoda files and examples are significantly out of date and likely still incomplete. In the meantime, I would suggest using the sample ODM2 database I have created instead. There are complete examples for both MySQL and Microsoft SQL Server. I don't have a public database that you could connect to (and USU's firewalls would block it anyway). But, you could easily stand up either on a dev server there.  Here's the link to the examples:

https://github.com/ODM2/ODM2/tree/master/usecases/littlebearriver/sampledatabases

**Comment by cdesyoun** [comment]
Jeff, I deployed this sample data into mysql server for testing. And I fixed some bugs for odm2 timseries example based on this data. I realized sqlalchemy queries are slightly different based on database types (postgreSQL and mysql). In my case, the "distinct" keyword in sqlalchemy's query statement, even if it is working in postgreSQL db, is not working for mysql database so that I used "group_by" keyword instead. 

Here are test sites below:
http://sis-devel.cloudapp.net:8080/ODM2Measurement/
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest_1_0/
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest_1_1/
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest_2/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_1_0/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_1_1/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_2/

**Comment by horsburgh** [comment]
@cdesyoun - cool. I've been clicking through these and things seem to be working with the new testing database. Thanks for setting that up.  At first glance, there seem to be a few things missing in the WaterML responses.  I will try to summarize a list when I get a chance.

**Comment by valentinedwv** [comment]
closing.
opened #34
