### ISSUE TITLE
GetSites is failing with a 405

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#29]
GetSites is failing with a 405 error when you access it via the CUAHSI test page:
http://hiscentral.cuahsi.org/testpage.aspx?n=5574
Must be happening inside one of the libraries, because "405" is not present in the WOFpy code.
Logging isn't helping. For some reason it's throwing a 405 error without logging anything, nor does it return a text message.

Needless to say (because SOAP sucks and REST rules), http://rths.us:8088/GetSites works a champ. SOAP needs to be shot in the head, dumped in a compost heap, and sprinkled with lime. AND EVEN THEN IT WILL COME BACK AS ZOMBIE SOAP, sigh.

I tested it with this form: http://www.service-repository.com/client/input?operation=GetSites&wsdlURL=http%3A%2F%2Frths.us%3A8088%2Fsoap%2Fwateroneflow.wsdl&portType=WaterOneFlow and filled in REON as the network name, and got this error:
[error.txt](https://github.com/ODM2/WOFpy/files/38180/error.txt)
Is that error related to the error that CUAHSI is seeing? I think not, because it's throwing a 500 error:
[500.txt](https://github.com/ODM2/WOFpy/files/38189/500.txt)

**Comment by valentinedwv** [comment]
Think this is an HIS issue. It does not actually sniff out the service endpoint.
Try changing the WSDL to the endpoint:
http://rths.us:8088/soap/wateroneflow/

Also, it you dare, you might try the new release. Not yet in pypi.

**Comment by cdesyoun** [comment]
I test the service endpoint, http://rths.us:8088/soap/wateroneflow.wsdl on soapui and membrane tools.
In soapUI tool, on request message,
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://www.cuahsi.org/his/1.0/ws/">
   <soapenv:Header/>
   <soapenv:Body>
      <ws:GetSites>
      <!--Optional:-->
         <ws:site>
            <!--Zero or more repetitions:-->
            <ws:string>REON:Stillwater</ws:string>
         </ws:site>
         <!--Optional:-->
         <ws:authToken>?</ws:authToken>
      </ws:GetSites>
   </soapenv:Body>
</soapenv:Envelope>
```
on response
```
<senv:Envelope xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:plink="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:senc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s0="http://www.cuahsi.org/his/1.0/ws/" xmlns:s12env="http://www.w3.org/2003/05/soap-envelope/" xmlns:s12enc="http://www.w3.org/2003/05/soap-encoding/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:senv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <senv:Body>
      <s0:GetSitesResponse>
         <sitesResponse xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:wtr="http://www.cuahsi.org/waterML/" xmlns="http://www.cuahsi.org/waterML/1.0/">
            <queryInfo>
               <criteria>
                  <locationParam>Zero or more repetitions:,REON:Stillwater</locationParam>
               </criteria>
               <note/>
               <extension/>
            </queryInfo>
            <site>
               <siteInfo xsi:type="SiteInfoType">
                  <siteName>Stillwater</siteName>
                  <siteCode siteID="2" network="REON">Stillwater</siteCode>
                  <timeZoneInfo siteUsesDaylightSavingsTime="false">
                     <defaultTimeZone ZoneOffset="00:00" ZoneAbbreviation="GMT"/>
                  </timeZoneInfo>
                  <geoLocation>
                     <geogLocation srs="EPSG:4269" xsi:type="LatLonPointType">
                        <latitude>42.9396971</latitude>
                        <longitude>-73.648872</longitude>
                     </geogLocation>
                  </geoLocation>
                  <note title="County">Saratoga</note>
                  <note title="State">NY</note>
                  <extension/>
                  <altname/>
               </siteInfo>
               <seriesCatalog/>
               <extension/>
            </site>
         </sitesResponse>
      </s0:GetSitesResponse>
   </senv:Body>
</senv:Envelope>
```
Also, membrane soap client test, it went well.

**Comment by cdesyoun** [comment]
Russ, in addition, your error message are due to just providing the network name only. Please provide the network name:site code (for example, REON:Stillwater) or just site code ( for example, Stillwater).

**Comment by RussNelson** [comment]
valentinedwv's advice worked for me.
cdesyoun: Sorry, why would GetSites require anything but the bare network name? Isn't the whole point of GetSites that you don't (yet) know any of the site names? Yes, if I know "Stillwater", then I can request it from GetSites, but GetSites is supposed to return a list of sites, not data from a single site. Either that, or I'm a moron.

**Comment by RussNelson** [comment]
I can reproduce your success with membrane, cdesyoun, by using the http://rths.us:8088/soap/wateroneflow/
url rather than the .wsdl url. I just leave the Network input box empty.

So why is WOFpy announcing the .wsdl URL rather than the / URL? Is the .wsdl technically correct, but clients don't know how to use it properly?? Maybe WOFpy should warn people about that, and give them the correct and the working URLs?

**Comment by valentinedwv** [comment]
Added issue #31

**Comment by valentinedwv** [comment]
GetSites does not need anything. An empty name normally returns all sites.
