### ISSUE TITLE
Automatic run of Soap and Rest Services  Multiple Service Helper class

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#3]
examples/runserver_multiple.py 
includes the ability to run multiple sources and multiple servers (rest/soap)

Create a helper class to create multiple data sources server based on a configuration file (it could point to other config files). 
This will greatly help with CZOData configurations.

**Comment by emiliom** [comment]
FYI, I don't know about examples/runserver_multiple.py, but I can vouch that the WOFpy adaptation that Stroud has been running for a while does have REST and SOAP services. @SRGDamia1 can describe that, if needed. You can see sample (but live) REST requests from the Stroud server at 
http://71.185.29.35:8080 and the WSDL at http://71.185.29.35:8080/soap/wateroneflow.wsdl. I think that REST and SOAP capability came straight from WOFpy, not something Stroud added.

**Comment by valentinedwv** [comment]
You using the soap interface for the calls?
Just because the wade,is there, does not mean the soap interface is initialized.

**Comment by emiliom** [comment]
Yeah, the soap interface. AFAIK, ulmo [initializes the soap interface](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cuahsi/wof/core.py).   

But no worries. I was just curious.

**Comment by SRGDamia1** [comment]
I definitely didn't create the SOAP interface myself.  I'm pretty sure it came from WOFpy.  It's possible that Justin set it up when he was working on it two years ago, but I don't think so.

**Comment by valentinedwv** [comment]
Can you send the run server file that being used 
Direct email...

**Comment by valentinedwv** [comment]
Ignore.
The Core.WOF.createWofApp takes care of this.
def create_wof_app(dao, config_file):
    """
    Returns a fully instantiated WOF wsgi app (flask + soap)
    """

**Comment by valentinedwv** [comment]
Reopened to make it simpler to create a multiple datasource server.

**Comment by valentinedwv** [comment]
preparation for this. Paths are now based on the network name. 
changeset: e0151a705eb63c6b635d1367c724f1945dfa43ce

**Comment by valentinedwv** [comment]
Closing.  new enhancement to read a set of config files in a directory, and load them.
Thought needed. One server type or multiples. etc.
