### ISSUE TITLE
Add note of WSDL to use in HIS central to Flask index.html page

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#31]
While the wsdl's are correct, HIS central needs a bit of a hack to work:
http://127.0.0.1:8080/LBR/soap/cuahsi_1_0/.wsdl

So add text to say in HIS central, and possibly other clients use the service location endpoint URL's
http://127.0.0.1:8080/{network}/soap/cuahsi_1_0/
http://127.0.0.1:8080/{network}/soap/cuahsi_1_1/

**Comment by cdesyoun** [comment]
David, I added some notes for soap service in HIS central.
And I redeployed it on test sites:

Service endpoints
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest/1_0
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest/1_1
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest/2
http://sis-devel.cloudapp.net:8080/ODM2Measurement/soap/cuahsi_1_0
http://sis-devel.cloudapp.net:8080/ODM2Measurement/soap/cuahsi_1_1
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest/1_0
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest/1_1
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest/2
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/soap/cuahsi_1_0
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/soap/cuahsi_1_1

Acess HTML descriptions of endpoints at 
http://sis-devel.cloudapp.net:8080/ODM2Measurement/
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest_1_0/
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest_1_1/
http://sis-devel.cloudapp.net:8080/ODM2Measurement/rest_2/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_1_0/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_1_1/
http://sis-devel.cloudapp.net:8080/ODM2Timeseries/rest_2/
