### ISSUE TITLE
HydroDesktop vs WOFpy, rrrrrrumble in the Bronx!

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#32]
Downloaded the latest HydroDesktop, running WOFpy from git HEAD, I try to download some of my data, and I get the enclosed error message. Not sure why HydroDesktop could or would transmit XML which is in error. Given that WOFpy is throwing the error, I'd expect it to be better about reporting it. For example, instead of letting the bare error be thrown, I'd expect something like this:

mydata = sys.stdin.read()
try:
  myhash = xml.parser(mydata)
except:
  print mydata
  raise

This way, when bad data arrives, you know what it looks like and can at least eyeball it. Easier said than done, of course, because the data is read in soaplib and parsed in lxml, which you don't have any control over.

[error2.txt](https://github.com/ODM2/WOFpy/files/39242/error2.txt)

**Comment by valentinedwv** [comment]
Agreed. That error looks deep in the network stack. Something is not getting converted to XML... Thinking about it, there were a couple of None errors that we fixed in the ODM2/WofPy codebase

 I get a 404 error for every port 8080 UR from hydrodesktop. I put in. Never even hits my localhost service.

**Comment by RussNelson** [comment]
/me spanks hydrodesktop. Any idea how to turn on logging for the request?

**Comment by valentinedwv** [comment]
HD Changing the CaSE of the path.
so:
http://127.0.0.1/LBR/soap/cuahsi_1_0/

becomes:
http://127.0.0.1/lbr/soap/cuahsi_1_0/

which in the python wsgi world is a different resource.

**Comment by valentinedwv** [comment]
As for logging. What is the standard way to up the logging level for python... learning myself.

**Comment by valentinedwv** [comment]
new source version published.
