### ISSUE TITLE
hiscentral fails to harvest, millions starve

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#33]
Jon reports "Martin – I tried to harvest but returned “there is an error in the XML document (225, 71).” …the harvest fails." On that query, soaplib is giving me this error: "DEBUG:soaplib._base:Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration. -- falling back to str decoding."

Perhaps I shouldn't be using HEAD? Is there a production-ready version of the code?

**Comment by valentinedwv** [comment]
SoapLib... 
Can you try ODM2/WOFpy/ source release? It's been moved to sypne.io

https://github.com/ODM2/WOFpy/releases/tag/v2.0.003-alpha

**Comment by RussNelson** [comment]
sypne.io isn't a valid domain name.
I'm not sure about the 003-alpha release. Part of the problem is that hiscentral harvesting isn't under my control, so I don't know exactly when they'll be harvesting. I switched between different WOFpy versions yesterday. I'm currently running the swtools/WOFpy HEAD. It might be working. Seems to have been harvested by the dev server but not the production server??

**Comment by emiliom** [comment]
@valentinedwv probably meant http://spyne.io

**Comment by valentinedwv** [comment]
Still waiting on a harvest

**Comment by RussNelson** [comment]
I got a successful harvest last night, with the cuahsi_1_0 endpoint. Green check mark! http://hiscentral.cuahsi.org/pub_network.aspx?n=5574

Have changed it to _1_1. Will check it tomorrow on Thanksgiving Day to make sure that it's still harvesting. No, actually, I'll be stuffing myself with turkey and stuffing. Happy Thanksgiving!

**Comment by valentinedwv** [comment]
Still green... so let's close this
