### ISSUE TITLE
Can odm_mysql be merged with odm_sqlserver?

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#38]
examples/odm_mysql has changes for lower case table names
examples/odm_sqlserver is the original code.

Can these be merged to just have an odm_1_1 example?

Quick test says, yes. 
Does the USU group a have example odm1 mysql, and postgres db's that could be tests

**Comment by horsburgh** [comment]
@valentinedwv - There are sample ODM 1.1.1 databases, including one for MySQL at:

http://hydroserver.codeplex.com/wikipage?title=Observations%20Data%20Model&referringTitle=Documentation

It's been a while, but I think we made the samples so they contain the same dataset.

**Comment by RussNelson** [comment]
I have some improvements to the mysql database. I split it into three parts: the invariant part that sets up the tables, the controlled variable part (which I download from cuahsi and turn into sql), and the site-dependent stuff, like sources, sites, variables, and methods. I think it would be reasonable to share the invariant and cv parts, and also supply a "populate with sample data" .sql file.

**Comment by valentinedwv** [comment]
complete
