### ISSUE TITLE
Test soap interface

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#4]
Example is here:
http://water.sdsc.edu/lbrsdsc/

use SOAPUI to test
localhost:8080/soap/wateroneflow.wsdl

Future:
localhost:8080/soap/wateroneflow_1_1.wsdl

**Comment by emiliom** [comment]
Dave, is this test running WOFpy on top of the USU-LBR **ODM2** database?? I'm just curious; if it is, that's really cool!

**Comment by valentinedwv** [comment]
yes. 
Choonhan has (had) it working over an ODM2.
I borked it when I started to adding WaterML 1.1

Discovered SOAP instances were not being initialized so that's why CUAHSI did not like it

**Comment by emiliom** [comment]
Thanks. I'm no SOAP expert, so I don't fully understand what you're describing; but I don't remember running into any problems consuming WOFpy services using SOAP, with both suds or ulmo (which uses suds). Could you explain this a bit:
> SOAP instances were not being initialized so that's why CUAHSI did not like it

or point me to an explanation online? That'd be helpful to me. Thanks.

**Comment by valentinedwv** [comment]
I assumed it was soap no initialized, it was actually, bug.
GetSites/GetSitesXml broken.
Rest Interface no sites, works.
Soap interface, no sites returned an error

**Comment by emiliom** [comment]
Great. So that means that wasn't the reason CUAHSI HIS Central hasn't liked WOFpy endpoints?

**Comment by valentinedwv** [comment]
.
Not being able to get a list of sites would probably stop them
harvesting...

**Comment by valentinedwv** [comment]
Tested 1.1 on Oct 15. Comments sent direct.

**Comment by cdesyoun** [comment]
I fixed them.

**Comment by valentinedwv** [comment]
Completed.
Need to see if we can register a waterml 1.1 endpoint with cuahsi. any volunteers

**Comment by emiliom** [comment]
Does the WDC have a test version of their catalog/registry? If so, it's fine with me if you or Choonhan want to try to register my Marchantaria use case, just for testing. If not, I'd rather not; it's too incomplete and unchecked for it to be publicly exposed.
