### ISSUE TITLE
Option to Lossen up the Network and Vocabulary match

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#42]
The code is pretty restrictive on matching the Network Naming. 
           siteCodesArr = [s.replace(self.network + ':', '')
                            for s in siteCodesArr]
Allows for strict matching of the network name, and normal new user no network name at the start.
Need option to allow for any network name (especially for testing).

Create a core method that can be used to do the separation, and optional strict validation, that can be used in both core_1_0 and core_1_

Same for vocabulary

**Comment by RussNelson** [comment]
Interesting you should say that, because REON:Marist isn't working for me right now, while the bare Marist is working. This is while using GetSiteInfoObject.

**Comment by RussNelson** [comment]
But "reon:Marist" does work. Color me confused.

**Comment by valentinedwv** [comment]
put a hack in to make Hydrodesktop work.
need to better note this .
https://github.com/ODM2/WOFpy/issues/35

**Comment by lsetiawan** [comment]
Any news on this issue?

@ocefpaf @emiliom
