### ISSUE TITLE
"Start tag expected, '<' not found, line 1, column 1"

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#43]
I'm running HEAD, and I'm up to date. If I try to fetch my site's metadata using HydroDesktop, it gives me the error in the subject. More precisely this:

ERROR:spyne.protocol.soap.soap11.invalid:XMLSyntaxError(u"Start tag expected, '<' not found, line 1, column 1",) in string u'\ufeff<?xml version="1.0" encoding="utf-8"?>\r\n<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <soap:Body>\r\n    <GetSiteInfoObject xmlns="http://www.cuahsi.org/his/1.0/ws/">\r\n      <site>reon:Marist</site>\r\n      <authToken>\r\n      </authToken>\r\n    </GetSiteInfoObject>\r\n  </soap:Body>\r\n</soap:Envelope>'
INFO:werkzeug:128.153.100.216 - - [23/Nov/2015 17:29:04] "POST /reon/soap/cuahsi_1_0 HTTP/1.1" 500 -

The *first* query succeeds, which is GetSites. Every GetSiteInfoObject query after that fails with the same error. The connection is being held open. If I look at the query that is being sent by using tcpdump, I can save it to a file and run it by hand. When I do that, it succeeds. SAME QUERY.

Doesn't it sound like something is being carried over from one HTTP query into the next? Is it the \ufeff ? This, it looks like: https://en.wikipedia.org/wiki/Byte_order_mark . Is spyne possibly not expecting a unicode string to start with the byte order mark?

**Comment by valentinedwv** [comment]
Not sure, dont' remember seeing this when running in PyCharm.

perhaps:
change the validator='lxml' 
to 
validator='soft'
in the core.py   soap_xx applications?

Might have to drop in a couple of events to see exactly what's happening
http://spyne.io/docs/2.10/reference/server.html

**Comment by valentinedwv** [comment]
And not seeing this locally:
HD 1.7.2.78
 running in a pycharm started instance of wofpy on 127.0.0.1:8080 windows
python 2.7.10 
both 1_1 and 1_0 endpoints
```
INFO:werkzeug:127.0.0.1 - - [23/Nov/2015 17:21:48] "GET /lbr/soap/cuahsi_1_1 HTTP/1.1" 405 -
DEBUG:spyne.protocol.xml:Validated ? True
DEBUG:root:[u'']
DEBUG:root:
INFO:werkzeug:127.0.0.1 - - [23/Nov/2015 17:22:19] "POST /lbr/soap/cuahsi_1_1 HTTP/1.1" 200 -
DEBUG:spyne.protocol.xml:Validated ? True
INFO:werkzeug:127.0.0.1 - - [23/Nov/2015 17:22:19] "POST /lbr/soap/cuahsi_1_1 HTTP/1.1" 200 -
DEBUG:spyne.protocol.xml:Validated ? True
[snip]
```

**Comment by cdesyoun** [comment]
Thanks for checking this, David.
Practically, I have not seen this error before. If I can spawn it, it will be easier to find this problem.

**Comment by RussNelson** [comment]
I'm running Ubuntu LTS, Python 2.7.6. Looks like there's a unicode bug. I installed 2.7.10 and this problem has gone away. Since Ubuntu LTS comes with 2.7.6, it's likely that I won't be the only person running into this issue. We don't know which version *is* required, but we know that we can't work on 2.7.6.  I don't see any obvious way to tell setuptools to refuse to install on 2.7.6. Help?

**Comment by cdesyoun** [comment]
David,
Would you please test it on my development site, http://sis-devel.cloudapp.net:8080/odm2timeseries/?
It is using python 2.7.6 and Ubuntu (Linux sis-devel 3.16.0-31-generic #41~14.04.1-Ubuntu SMP) OS.
If you have same problems, I will try to change this code line below in spyned_1_0.py and spyned_1_1.py as follows:
```
   from @rpc(Array(Unicode), Unicode, _returns=AnyXml)
   to @rpc(Array(String), String, _returns=AnyXml)
```
But, I am not sure it will work on that.

**Comment by valentinedwv** [comment]
@cdesyoun working, but this issue is with the initial XML stream of the whole message, so I don't think that those are the issue. But go ahead and check in, anyway.

**Comment by valentinedwv** [comment]
@cdesyoun  Before you upgrade the python, can you pull the latest, and see if 
setup.py install rejects 2.7.6?

**Comment by cdesyoun** [comment]
David, yes, the installation is rejected.

azureuser@sis-devel:~/WOF/WOFpy$ sudo python setup.py install
Sorry, Issues with Python 2.7.6. Please upgrade to 2.7.10 or above 

Do we still need to debug this?

**Comment by cdesyoun** [comment]
David, I changed the validator from 'lxml' to 'soft' on core.py file and the parameter type from 'Unicode' to 'String' on spyned_1_0.py and spyned_1_1.py files.
I redeployed it on test site.
Would you please test it again to see if it is working on python 2.7.6?

**Comment by RussNelson** [comment]
It's not working for me, and this is what I see vis-a-vis 'lxml' and 'soft' in core.py:

nelson@left:~/RussNelson-WOFpy$ grep soft wof/core.py
        in_protocol=HttpRpc(validator='soft'),
        in_protocol=HttpRpc(validator='soft'),
        in_protocol=HttpRpc(validator='soft'),
nelson@left:~/RussNelson-WOFpy$ grep lxml wof/core.py
        in_protocol=Soap11(validator='lxml'),
        in_protocol=Soap11(validator='lxml'),

**Comment by cdesyoun** [comment]
Changes are on my development site, not on the github.
If it works, I will update it on the github.

**Comment by valentinedwv** [comment]
Nope. Changing does the validator  and object types does not appear to solve this.

So, no. Let's just set it to suggesting 2.7.10, in setup...

**Comment by cdesyoun** [comment]
OK, I stop debugging on python 2.7.6 version.
Then I will update python version from 2.7.6 to 2.7.10 on my test/development site.

**Comment by valentinedwv** [comment]
We upgrade the sis-devel.cloudapp.net server, still no go.

Even did a nice clean virtualenv, and still not working correctly.

(venv_odm)azureuser@sis-devel:~/WOF/WOFpy$ pip list
Flask (0.10.1)
GeoAlchemy2 (0.2.6)
itsdangerous (0.24)
Jinja2 (2.8)
lxml (3.5.0)
MarkupSafe (0.23)
mysql (0.0.1)
MySQL-python (1.2.5)
nose (1.3.7)
numpy (1.10.1)
ODM2API (0.1)
pandas (0.17.1)
pip (7.1.2)
postgres (2.2.1)
psycopg2 (2.6.1)
PyMySQL (0.6.7)
pyodbc (3.0.10)
python-dateutil (1.5)
pytz (2015.7)
setuptools (18.2)
six (1.10.0)
spyne (2.12.11)
SQLAlchemy (1.0.9)
Werkzeug (0.11.2)
wheel (0.24.0)
WOFpy (2.0.7a0, /home/azureuser/WOF/WOFpy)

**Comment by RussNelson** [comment]
FWIW, I have:
lxml 3.4.4
MySQL-python 1.2.3
numpy 1.8.2
pip 1.5.4
pytz 2015.4
setuptools 3.3
six 1.5.2
SQLAlchemy 0.8.4
Werkzeug 0.10.4
and WOFpy HEAD

**Comment by valentinedwv** [comment]
I suspect it's the new lxml.
on sis-devel
removed lxml 3.5, installed 3.4.4 works.

pip uninstall lxml
pip install lxml==3.4.4

**Comment by cdesyoun** [comment]
David, I installed HydroDesktop (HD) 1.4.11.1 version on my desktop window 7 pro.
When trying to harvest soap service 1.0, I still got the same error which Russ got.
Because of BOM (\ufeff) in the request, lxml lib (supports only the encoding type, 'UTF-8') can not encode/decode the request message. In spyne package, I looked into "spyne/protocol/soap/soap11.py".
Within this file, this function below raised the exception error. For testing, I changed the encoding type from 'utf-8' to 'utf-8-sig'. It was worked. It seems to me it is a bug for spyne package.
```
def _parse_xml_string(xml_string, parser, charset=None):
    string = b''.join(xml_string)
    if charset:
        #string = string.decode(charset)
        string = string.decode('utf-8-sig') # remove BOM
        string = string.encode(charset) # back to original encoding type
    try:
        try:
            root, xmlids = etree.XMLID(string, parser)

        except ValueError as e:
            logger.debug('ValueError: Deserializing from unicode strings with '
                         'encoding declaration is not supported by lxml.')
            root, xmlids = etree.XMLID(string.encode(charset), parser)

    except XMLSyntaxError as e:
        logger_invalid.error("%r in string %r", e, string)
        raise Fault('Client.XMLSyntaxError', str(e))

    return root, xmlids
```

**Comment by cdesyoun** [comment]
And, David, I guess you did test WOFpy using my own modified spyne package above deployed on sis-devel host while I am working on. After changing lxml version as you suggested, I switched original spyne version. It did not work. I think when we add two lines in above function, at least, within HydroDesktop WOFpy will work correctly without encoding problem.

**Comment by valentinedwv** [comment]
Different thought.
can we see if it's flask?
aka try the standard python wsgi app, without the html pages (no flask).

**Comment by valentinedwv** [comment]
Can that be a method_call event in the service classes?

http://spyne.io/docs/2.10/reference/service.html

**Comment by cdesyoun** [comment]
In WOFpy, I think soap service is related to wsgi app, not flask app.
And I tried to capture event handlers in service and application classes.
In service class, "method_call" event happens after making request including BOM tag so that it is no use of it. That is, the error exception was raised already. In application class in spyne, when used "method_context_created" event, most of variables in "wsgiMethodofContext" class were empty so that I could not get soap request message from a client to remove BOM tag. Maybe, "before_deserialize" event is possible but in WOFpy code, I have no idea where to add it.
That's why I modify the encoding part in sypne code.

**Comment by valentinedwv** [comment]
Can you inherit the soap_1_1 class, override _parse_xml_string
and use that in WofPy

**Comment by cdesyoun** [comment]
OK, I will try on it.

**Comment by cdesyoun** [comment]
David, I caught this event. The "ctx.in_string" variable which contains soap request has object type. But converting string is still empty.
Instead, I overrode "create_in_document" function below in soap11.py in wof/core.py.
It works fine. I updated it on github.

```
class wofSoap11(Soap11):
    def _wof_parse_xml_string(self, xml_string, parser, charset=None):
        string = b''.join(xml_string)
        if charset:
            #string = string.decode(charset)
            string = string.decode('utf-8-sig') # remove BOM
            string = string.encode(charset) # back to original encoding type
        try:
            try:
                root, xmlids = etree.XMLID(string, parser)

            except ValueError as e:
                logger.debug('ValueError: Deserializing from unicode strings with '
                         'encoding declaration is not supported by lxml.')
                root, xmlids = etree.XMLID(string.encode(charset), parser)

        except XMLSyntaxError as e:
            logger_invalid.error("%r in string %r", e, string)
            raise Fault('Client.XMLSyntaxError', str(e))

        return root, xmlids

    def create_in_document(self, ctx, charset=None):
        if isinstance(ctx.transport, HttpTransportContext):
            # according to the soap via http standard, soap requests must only
            # work with proper POST requests.
            content_type = ctx.transport.get_request_content_type()
            http_verb = ctx.transport.get_request_method()
            if content_type is None or http_verb != "POST":
                ctx.transport.resp_code = HTTP_405
                raise RequestNotAllowed(
                        "You must issue a POST request with the Content-Type "
                        "header properly set.")

            content_type = cgi.parse_header(content_type)
            collapse_swa(content_type, ctx.in_string)

        ctx.in_document = self._wof_parse_xml_string(ctx.in_string,
                                            XMLParser(**self.parser_kwargs),
                                                                        charset)
 ```

**Comment by valentinedwv** [comment]
Can you put it on a branch so we can test it?

**Comment by cdesyoun** [comment]
Yes, I have already put the 'master' branch. You can pull it out.
