### ISSUE TITLE
value outside of enum for .....

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#45]
I notice that core_1_0 is checking the UnitsType against a list of units, and throwing a warning and throwing the "invalid" unit away and replacing it with "dimensionless". Perhaps we should change the warning so it says something like "UnitsType not in 1.0 CV. Should you use the .../cuahsi_1_1 URL?" It's always better to give people a warning or error that points them in the direction of repair.

**Comment by valentinedwv** [comment]
Yes, suggestion is to use the 1_1 endpoint.

In 1.0, many vocabularies for WaterML were embedded and fixed, so even if it's now in the CV, its not valid in WML 1.0.

Probably should change to Info, and improve the messages

**Comment by valentinedwv** [comment]
INFO:root:Substituted 'Dimensionless'. WaterML 1.0 schema enum issue 'Turbidity' not in UnitsType. Use the cuashi_1_1 endpoint
INFO:root:Substituted 'Dimensionless'. WaterML 1.0 schema enum issue 'Concentration' not in UnitsType. Use the cuashi_1_1 endpoint
