### ISSUE TITLE
Fault: Fault(Server: 'unconverted data remains: Z')

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#47]
Trying to read one variable (temperature) from one site (Esperance). Seems to be making great progress. Get the site, gets the spatial reference, gets the variable, gets the units, (96L, 'degree celsius', 'Temperature', 'degC'), searches for another unit, gets it: (100L, 'second', 'Time', 's') but immediately thereafter, I get this error and traceback:
ERROR:spyne.application:Fault(Server: 'unconverted data remains: Z')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spyne-2.12.11-py2.7.egg/spyne/application.py", line 151, in process_request
    ctx.out_object = self.call_wrapper(ctx)
  File "/usr/local/lib/python2.7/site-packages/spyne-2.12.11-py2.7.egg/spyne/application.py", line 235, in call_wrapper
    retval = ctx.descriptor.service_class.call_wrapper(ctx)
  File "/usr/local/lib/python2.7/site-packages/spyne-2.12.11-py2.7.egg/spyne/service.py", line 209, in call_wrapper
    return ctx.function(ctx, *args)
  File "/home/nelson/WOFpy/wof/apps/spyned_1_1.py", line 181, in GetValuesObject
    raise Fault(faultstring=str(inst))
Fault: Fault(Server: 'unconverted data remains: Z')
INFO:werkzeug:128.153.100.216 - - [01/Dec/2015 11:10:16] "POST /reon/soap/cuahsi_1_1 HTTP/1.1" 500 -

If I may be permitted a bit of speculation, I notice that it looks for time units, and then immediately thereafter it has a problem with an unconverted "Z" as in Zulu as in UTC, which is the time zone we're using. Is it possibly trying to convert a time that has a Z in it? I think that the real location of the exception is being hidden in the trackback above.

**Comment by RussNelson** [comment]
I took out the try/except from spyned_1_1.py at line 181 and got a better traceback. It looks like my speculation was correct: it's trying to convert a datetimeUTC that has a Z at the end.
[trackback.txt](https://github.com/ODM2/WOFpy/files/48775/trackback.txt)

**Comment by valentinedwv** [comment]
Yeah, I had a feeling we would hit this somewhere else in the code after I fixed some time parsing in the  csv codebase, and implemented timezones using pytz

Original code passed dates as iso strings.... better to pass datetime objects with timezone set using pytz

code needs to use dateutils.parser.parse, and not custom parse strings

for examples, see csv_dao 
create_datavalue_from_row
parse_date_strings

**Comment by RussNelson** [comment]
Adding a "Z" to the end of the conversion string in line 3053 in WaterML_1_1.py fixes it for me:
            initvalue_ = datetime_.datetime.strptime(dateTimeUTC, '%Y-%m-%dT%H:%M:%SZ')
I'm not familiar enough with the code to want to submit it as a fix for everyone, however.

**Comment by valentinedwv** [comment]
I'd say let's fix it higher in the code to use objects (core), and not strings.

**Comment by RussNelson** [comment]
I'm under a two-week deadline to teach my boss how to use HydroDesktop, which means that I need WOFpy to be working, so I have to run with "works for me" for now...

**Comment by valentinedwv** [comment]
Yes.

**Comment by valentinedwv** [comment]
I think we have this done.
