### ISSUE TITLE
Download/usage Logging

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#48]
We want to know how often the service is accessed, and what is access.
Add usage logging to a file.

| date| (START/END)| network| method| sitecode|variablecode| begindate|endDate| resultCount | response time

**Comment by valentinedwv** [comment]
And perhaps a daily/since start accumulation to a file. (hey, improve upon original wateroneflow logging)

**Comment by lsetiawan** [comment]
What's going on with this issue?

@ocefpaf @emiliom
