### ISSUE TITLE
Release as "1.0" instead of "2.0"?

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#49]
The WOFpy overhauls are being [flagged as building towards a "2.0" release](https://github.com/ODM2/WOFpy/releases). But there was never a WOFpy 1.0; in its original development, it stayed only with alpha tags that reached a 0.1.1 version. Back in early October @cdesyoun [tagged the initial enhancements as 0.2](https://github.com/ODM2/WOFpy/tags).

I know this may be quibbling, but to me it seems more natural and less conducive to confusion by users to release a "1.0" version instead. I also realize that it may be too late b/c the last many releases, plus milestones, have already been tagged as 2.0alpha, etc. But it doesn't hurt to bring this up anyway ...

1.0 or 2.0, WOFpy is looking great! I'm looking forward to having the time to test it out. Maybe during AGU.

**Comment by valentinedwv** [comment]
I looked at the breaking changes from when we moved to spyne as the reason to skip 1.0.  It announces that this is a different codebase, and not a progression from the 0.x codebase.
Mostly compatible, but with many breaking changes

**Comment by emiliom** [comment]
Got it. Thanks.
