### ISSUE TITLE
Werkzeug says don't use debugger in production

### ISSUE THREAD

**Issue by RussNelson** [ODM2/WOFpy#50]
Werkzeug says don't use debugger in production: http://werkzeug.pocoo.org/docs/0.11/debug/#enabling-the-debugger
I'm not 100% that we're actually doing that, however when it starts up, it prints a debugger PIN code, which is what Werkzeug says the debugger does.
We shouldn't ship the release with debugging turned on, because someone who isn't a developer might not know that debugging was turned on.
Remember the sendmail debug worm?

**Comment by cdesyoun** [comment]
Russ, debuggers are removed in "core.py". For this, I added it below:
```
logging.disable(logging.CRITICAL)
```

**Comment by cdesyoun** [comment]
I changed the debug type in "core.py" file. when disabling the debugger, I realized users can not debug WOFpy at all.
```
logging.getLogger('werkzeug').setLevel(logging.CRITICAL)
```

**Comment by valentinedwv** [comment]
Choonhan,
Loggers should be fine

Russ,
I don't think it's enabled, unless we
```
app = DebuggedApplication(app, evalex=True)
```

spoke too soon in runserver_odm_1_1.py
```
   app.config['DEBUG'] = True
```

**Comment by RussNelson** [comment]
Yeah, I think we need to remove or comment-out that line. If commented-out, include the link above in a comment saying #do not debug a server the public can access: http://werkzeug.pocoo.org/docs/0.11/debug/#enabling-the-debugger
