### ISSUE TITLE
Demonstrate logging using config files then doco

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#51]
https://docs.python.org/2/library/logging.config.html

**Comment by lsetiawan** [comment]
Anyone know the status of this issue?

@ocefpaf @emiliom

**Comment by ocefpaf** [comment]
The issue description is not very clear to me. I am guessing that the goal is not to demostrate but rather implement a logging scheme for wofpy. If so I don't think we have one.

That is not an an easy task BTW, but we can certanily start logging some of the key outputs.

**Comment by lsetiawan** [comment]
@ocefpaf No worries, just trying to clean up, don't address just simply checking 😄

**Comment by ocefpaf** [comment]
IMO we should treat any 2-year issue like a Trello card. Just close it and wait for the original poster to re-open it if it is still relevant :smile:

**Comment by lsetiawan** [comment]
Good Idea! Thanks 😄
