### ISSUE TITLE
python-dateutil ==1.5.0

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/WOFpy#53]
Is there a strong reason to [pin](https://github.com/ODM2/WOFpy/blob/master/setup.py#L59) WOFpy to `python-dateutil ==1.5.0`? That is quite an old version!

**Comment by valentinedwv** [comment]
Not sure. Changelog @2.1 says there were some 2.6 and 2.7 issues.

**Comment by ocefpaf** [comment]
No problem. I will try to investigate this later. Meanwhile I will package `python-dateutil 1.5.0` for. the ODM2 channel.

**Comment by emiliom** [comment]
@ocefpaf, FYI, development on WOFpy stopped for abt. 4 years before @valentinedwv and a colleague of his picked it up last year and the ODM2 team became the new maintainers. A lot of work was done on it in the last 6 months, but it's not too surprising that it has some remnant old issues like this old dependency pinning. Hopefully we can get rid of it soon.

**Comment by ocefpaf** [comment]
No worries. I find that the process of packing forces me to dig into the software. So I will be sending PRs to WOFpy soon to help with that.

**Comment by valentinedwv** [comment]
Go ahead and update requirements. No difference in dates.

Working on updating the tests. May be a bit since they are out of date

**Comment by ocefpaf** [comment]
Thanks @valentinedwv. I will close this then.
