### ISSUE TITLE
timeOffset issue with CSV example

### ISSUE THREAD

**Issue by mmbayles** [ODM2/WOFpy#56]
I noticed an issue with time offset using the CSV example included with WOFpy. 
This screenshot is of the standard waterml 1.1 example provided by CUAHSI. The time offset is in a separate tag. 
![image](https://cloud.githubusercontent.com/assets/12237799/14959840/9c31a1c2-104e-11e6-85a3-ec9b48bb6cb3.png)

However, when I run the csv example the time offset is included in the dateTime tag. 
![image](https://cloud.githubusercontent.com/assets/12237799/14959922/34018d78-104f-11e6-8531-2d6b06c6c3f8.png)

Is there a reason for this difference or am I misunderstanding something?

**Comment by valentinedwv** [comment]
Thanks. 
We will need to make it conform to the expected

**Comment by lsetiawan** [comment]
The status of this issue is unknown. Closing for now, until problem arise again.
