### ISSUE TITLE
SOAP GetSites/GetSitesXML error when site does not exists. 

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#6]
If the site does not exist, or if the site is EmptyString, I still get a 
'NoneType' object 
Just return message 'Site Not Found'

**Comment by cdesyoun** [comment]
David, Instead of "<site/>" tag which I did make first, I  put exception error containing the below message.
How about this?

   <senv:Body>
      <senv:Fault>
         <faultcode>senv:Server</faultcode>
         <faultstring>Site Not Found</faultstring>
         <faultactor/>
      </senv:Fault>
   </senv:Body>
