### ISSUE TITLE
Travis-CI is failing on master

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/WOFpy#64]
It seems that the tests are failing in latest `master`. I am putting together a PR to add some Python 2/3 compatibility changes, but we need to fix `Travis-CI` first in order to properly assess the PR. The failures are mostly at `test/test_odm2_dao_sqlite.py`. See https://travis-ci.org/ODM2/WOFpy/ for the full log.

xrefL #63 and #62

**Comment by ocefpaf** [comment]
Re-opening because there are more failures that we need to address.

**Comment by emiliom** [comment]
Ok

**Comment by emiliom** [comment]
Travis-CI is still failing, right? I remember you said you were working on the last fixes to get that working. Do you expect to have a PR today?

cc @lsetiawan

**Comment by ocefpaf** [comment]
>  Do you expect to have a PR today?

Probably not. I am stuck there. Nothing that I tried worked. (Not even reverting to the last passing commit!)

**Comment by emiliom** [comment]
Ok, I just got a clarification from @lsetiawan. Right now, Travis-CI should **only** be running `test_wof.py`. **Nothing else.** Can you give that a try?

**Comment by ocefpaf** [comment]
Let me send a PR that will split the text context so we can run everything as is but leaving the `test_odm2_dao_sqlite.py` in a `allow_failure` section. That way we get an "all green" from Travis-CI but we can still see the failures (and work on them).

Sounds OK?

**Comment by emiliom** [comment]
Yeah, we like that!

**Comment by ocefpaf** [comment]
Closed by #98

Well.. Kind of :smile:
But let's open a fresh issue for `test_odm2_dao_sqlite.py`.

**Comment by emiliom** [comment]
Cool, thanks! Yup, we'll open a fresh issue when we're ready to try `test_odm2_dao_sqlite.py` again.
