### ISSUE TITLE
Broken WSDL links (and SOAP endpoints?) on WOFpy instance main page

### ISSUE THREAD

**Issue by emiliom** [ODM2/WOFpy#67]
@lsetiawan managed to get a production WOFpy instance up and running on the amazon cloud, with the test LBR ODM2 MySQL database. The [WOFpy instance start/main page is here](http://52.24.188.162:8080/odm2timeseries/). And FYI, his documentation/instructions on what he did is [here](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBRproduction_installation_notes.md).

The REST services all seem to work fine. But none of the WSDL links work; the SOAP endpoint links return what looks like sensible a message, though I don't enough about this:
```xml
<soap11env:Fault>
  <faultcode>soap11env:Client.RequestNotAllowed</faultcode>
  <faultstring>You must issue a POST request with the Content-Type header properly set.</faultstring>
  <faultactor/>
</soap11env:Fault>
```

Is the SOAP WOF service supposed to work -- ie, has it been tested? If so, maybe it's just a matter of that default WSDL link being incorrect? I haven't tested the SOAP endpoints with SOAP client.

Thanks, @valentinedwv

**Comment by valentinedwv** [comment]
No idea on the WSDL.

Did it work in runserver?

**Comment by valentinedwv** [comment]
think it can find, nor go outside of the top level www?

 sudo cp -r /home/ubuntu/WOFpy/examples/flask/odm2/timeseries /var/www/

curr_folder = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, '%s/../../../' % curr_folder)

**Comment by lsetiawan** [comment]
It doesn’t work, I get template not found errors on WSDL using the example runserver script.
--
Landung “Don” Setiawan, B.S.
Research Consultant 
EIS | Applied Physics Laboratory
University of Washington
landungs@uw.edu

**Comment by valentinedwv** [comment]
it wants to find these templates.

https://github.com/ODM2/WOFpy/tree/master/wof/flask/templates

**Comment by lsetiawan** [comment]
@valentinedwv So I should include a templates folder with my deployment? I thought this was brought in with the wofpy package.

**Comment by valentinedwv** [comment]
Or add a hard coded path to the templates.
  app= wof.flask.create_wof_flask_multiple({conf_swis, conf_lcm, conf_csv}, templates="../../wof/apps/templates")

unless you know of a way to get resources from installed eggs, like you can with jars

**Comment by lsetiawan** [comment]
@valentinedwv So, I solved the broken WSLD's thank to your suggestions. The WaterML2 seems to work also. SOAP is still not working though.

**Comment by lsetiawan** [comment]
I tested the SOAP Service here: http://www.plumvoice.com/soaptester/ and it seemed to work.

**Comment by emiliom** [comment]
Thanks, Dave and Don. Don, please update the document you've put together, when you get a chance.

I'll close this issue next week, once I've done more testing on the SOAP service.

**Comment by ocefpaf** [comment]
> unless you know of a way to get resources from installed eggs, like you can with jars

That is possible. I can take a look at implementing this later.
@lsetiawan it is a similar case to https://github.com/miguelcleon/ODM2-Admin/pull/96/commits/c32ee956fc6cda1e1be5892b88b592c59447f4db , then in the code we can use either [pkg-resources](http://setuptools.readthedocs.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources) or a clever `__filie__` and relative paths to find the packaged resources.

**Comment by emiliom** [comment]
@ocefpaf and @valentinedwv: yes, the plan is to implement a packaging and installation feature along these lines, later on. At least with conda. Let's finish the ODM2-Admin implementation first, though, so we can learn from that experience.

**Comment by ocefpaf** [comment]
> At least with conda.

The implementation works with with both `conda` and `pip`.

> Let's finish the ODM2-Admin implementation first, though, so we can learn from that experience.

Sure. But that one is a different beast... It is still unclear to me the right path forward. (But let us discuss this in https://github.com/miguelcleon/ODM2-Admin/pull/96)

**Comment by valentinedwv** [comment]
Need to access the files in an packaged release from the package.
Will need testing.

http://stackoverflow.com/questions/6028000/python-how-to-read-a-static-file-from-inside-a-package
http://stackoverflow.com/questions/3071327/problem-accessing-config-files-within-a-python-egg

**Comment by emiliom** [comment]
This issue was "fixed" (namely, we now know how to deploy SOAP and WSDL's properly) a few weeks ago. See @lsetiawan's [comment above from Jan 25](#issuecomment-275278345), and the WOFpy [installation documentation that implements the solution](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBRproduction_installation_notes.md). I'll leave the issue open for now, though, while we do more extensive testing.

**Comment by lsetiawan** [comment]
This issue is definitely fixed. Problems arise from templates path not defined correctly.
