### ISSUE TITLE
Database transaction rollback error

### ISSUE THREAD

**Issue by sreeder** [ODM2/WOFpy#69]
When a query to the database fails all succeeding requests return an error, "can't reconnect until invalid transaction is rolled back 
![screen shot 2017-03-01 at 1 25 30 pm](https://cloud.githubusercontent.com/assets/4721940/23479703/906af0fa-fe82-11e6-90b2-c55c12899c8a.png)
"

**Comment by emiliom** [comment]
Thanks, @sreeder. Can you provide an example of a query that fails? I think you said one of the sample REST query url's failed. If so, please paste the link here.

**Comment by sreeder** [comment]
@emiliom , I am actually  testing it now to try and get one to fail, but apparently it is happy today. I will keep testing and let you know as soon as I find one that fails. This is still something we should handle though, even if we can't figure out which one was failing for me. We don't want a user to have to come across this issue, and we have to restart all of the processes to get it to work again. I'm also wondering if there is a problem with the connection to the mysql database is timing out after it has been inactive for too long...but that is another issue

**Comment by emiliom** [comment]
> This is still something we should handle though, even if we can't figure out which one was failing for me.

Agreed. But having a specific example will help me reproduce the problem and look into it.

**Comment by emiliom** [comment]
@sreeder, as I mentioned in my email to the group a minute ago, I haven't run into this problem at all in our own LBR DB test deployment.

Let's leave this issue open for now in case the problem comes up again, or as a reference to follow up on (as you suggested) to ensure that there is proper error testing built in to prevent database locks.

**Comment by emiliom** [comment]
Closing. We haven't run into this problem again, with MySQL.

Referencing #133 in case the discussion here is helpful for that postgresql issue (I doubt it, plus it's pretty much solved).
