### ISSUE TITLE
can't connect to SOAP endpoint

### ISSUE THREAD

**Issue by sreeder** [ODM2/WOFpy#70]
I get an error after trying to connect to the SOAP endpoint. I get the correct information when I connect to the .wsdl

![screen shot 2017-03-01 at 1 49 39 pm](https://cloud.githubusercontent.com/assets/4721940/23480660/f7be5780-fe85-11e6-9532-02c7271474e6.png)

**Comment by sreeder** [comment]
Just noticed this is a duplicate of issue #67

**Comment by emiliom** [comment]
Issue #67 was solved, though, and the solution (setup instructions) should be found in @lsetiawan's [deployment instructions](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBRproduction_installation_notes.md). Let us know via issue #67 if you're still getting this error even though you followed the instructions step by step.
