### ISSUE TITLE
Non-fatal error "bad datetime conversion" messages

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#71]
- On http://127.0.0.1:8080/odm2timeseries/rest/1_1/GetSiteInfo?site=odm2timeseries:USU-LBR-Mendon and http://127.0.0.1:8080/odm2timeseries/rest/1_1/GetSiteInfoMultple?site=odm2timeseries:USU-LBR-Mendon I am getting these non-fatal errors
``` bash
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
ERROR:root:bad datetime conversion
```

**Comment by valentinedwv** [comment]
Some dates are not converting.

Could make the error more detailed error message, and not fatal. If there is no conversion, it defaults to to NOW:
Core1_1.py:731
        try:
            beginDateTime =  dateutil.parser.parse(beginDateTime)
            endDateTime =  dateutil.parser.parse(endDateTime)
        except Exception as inst:
              logging.error('bad datetime conversion')

        #TimeInterval
        if beginDateTime is None:
            beginDateTime = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
        if endDateTime is None:
            endDateTime = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

**Comment by emiliom** [comment]
Thanks, @valentinedwv. We haven't looked into this; at this point we just wanted to capture the issue before we forget. Thanks for digging into it! Like @lsetiawan said, the error is not fatal.

**Comment by emiliom** [comment]
@lsetiawan, I'm not sure why you added the section "Links to relevant WOFpy resources and documentation" on this issue. I don't think those links discuss anything specific to this issue. We may move that section out of [WOFpyODM2LBRtest_installation_notes.md](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBRtest_installation_notes.md) later on, but for now they're still there for reference. 

Unless I've missed something, please go ahead and delete that section from your original issue text. Thanks. FYI, I'm going to rename the issue to make it more specific.

**Comment by lsetiawan** [comment]
As of the latest WOFpy (https://github.com/ODM2/WOFpy/commit/cf12e131212b1bf7ffc9e04a49be88fee2fb6614) This is error is not there anymore. I'm closing unless it reappears.
