### ISSUE TITLE
Runserver arguments and wsgi entrypoint

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#81]
I am putting this as an issue because, I'm confused of which was is the way that WOFpy should be deployed. Currently, in the examples, the runserver scripts expect arguments, but this way doesn't work when I'm using uWSGI, which uses `wsgi.py` as the entrypoint.

So, when a user runs the `wofpy_config` CLI, should they get the configuration with this production setup in mind or the ones in examples, for just a quick test of WOFpy where they can just do `python runserver.py [arguments]`. Thanks.

**Comment by emiliom** [comment]
@lsetiawan, I don't know enough about WOFpy setup to follow what you're saying!

> Currently, in the examples, the runserver scripts expect arguments, but this way doesn't work when I'm using uWSGI, which uses wsgi.py as the entrypoint.

Aren't you using uWSGI/wsgi.py in your live deployment? If so, didn't you run the runserver scripts with arguments? 

> So, when a user runs the `wofpy_config` CLI, should they get the configuration with this production setup in mind or the ones in examples, for just a quick test of WOFpy where they can just do python runserver.py [arguments].

Good question about what `wofpy_config` should do (production vs test). Can we ultimately provide options to do both, but maybe focus on one initially? What do you recommend? I'm not even sure what  you man by "should they get the configuration". I thought `wofpy_config`, **for now**, was just copying files, nothing more.

**Comment by lsetiawan** [comment]
@emiliom 

> Aren't you using uWSGI/wsgi.py in your live deployment? If so, didn't you run the runserver scripts with arguments?

I did use `wsgi.py` but I had to tweak the `runserver.py` and defining the arguments values inside the script.

> Can we ultimately provide options to do both, but maybe focus on one initially? What do you recommend? I'm not even sure what you man by "should they get the configuration". I thought wofpy_config, for now, was just copying files, nothing more.

Yea, it is currently just copying the example files, but ultimately those files would be files for either production setup or testing setup. I was thinking that maybe the production setup would have the runserver script without the arguments, and the test would be the one with CLI arguments. 

@ocefpaf Any thoughts on this? Thanks.

**Comment by emiliom** [comment]
> I did use wsgi.py but I had to tweak the runserver.py and defining the arguments values inside the script.

Ah, I see.

I'll be good to hear what @ocefpaf has to say. But @lsetiawan, you're the pro here (among the 3 of us)! Can you lay out a detailed, clean suggestion? Can those argument you edited in the production setup be part of a separate json configuration file that the use would need to fill out, for a production environment? Or do users need to make other edits to `runserver.py` anyway?

**Comment by ocefpaf** [comment]
> I am putting this as an issue because, I'm confused of which was is the way that WOFpy should be deployed.

I am confused as well. I had the impression that copying the examples and letting the users edit them was the decision from https://github.com/ODM2/WOFpy/issues/72#issuecomment-290286459

> I was thinking that maybe the production setup would have the runserver script without the arguments, and the test would be the one with CLI arguments.
@ocefpaf Any thoughts on this? Thanks.

That seems OK IMO but I am not a WOFpy users to really say that is the best way.

PS: I am not even convinced that copying the examples is a good pattern. I am having a hard time getting Travis-CI back online and keeping the module internals "sane" that way.

**Comment by lsetiawan** [comment]
> I had the impression that copying the examples and letting the users edit them was the decision from #72 (comment)

Ah, I didn't quite remember that decision, if that's the case then that's fine to just keep it that way. I guess as long as we provide a good documentation of what should be changed.

> PS: I am not even convinced that copying the examples is a good pattern. 

Maybe we shouldn't just copy the examples, but maybe copy actual configuration files depending on the users need to either deploy it as testing or production?

**Comment by emiliom** [comment]
>  I had the impression that copying the examples and letting the users edit them was the decision from #72 (comment)

Yes, that was definitely the decision. *However*, that doesn't mean it's the only thing the `wofpy_config` CLI should do! We're trying to simplify the installation and configuration experience.  @lsetiawan raises good questions about `runserver.py` and production vs test configurations. Earlier (72#issuecomment-286749464) @ocefpaf made this suggestion:

> However, in the future we can simplify that further with a single YAML config file

That's all on the table for discussion. Though I'd like to hear more from Filipe about his comment:

> PS: I am not even convinced that copying the examples is a good pattern.

And Don's response:

> Maybe we shouldn't just copy the examples, but maybe copy actual configuration files depending on the users need to either deploy it as testing or production?

Maybe a Skype call would help? Say, Thursday?

**Comment by lsetiawan** [comment]
@emiliom Thursday won't work for me, as I have work lined up for Anthony's project. Can we do Friday? Thanks.

**Comment by emiliom** [comment]
Right, I forgot. Friday is actually better for me too.

**Comment by emiliom** [comment]
For reference, specially for @ocefpaf: [Here's our documentation on a production installation & configuration](docs/WOFpyODM2LBRproduction_installation_notes.md), which describes the changes done to `runserver.py`, at least for out canonical MySQL ODM2 Little Bear River sample database.

**Comment by ocefpaf** [comment]
Friday is fine for me.

PS: the link above is not found at https://github.com/ODM2/WOFpy/issues/docs/WOFpyODM2LBRproduction_installation_notes.md

**Comment by emiliom** [comment]
Re: doc url: sigh. I tried a relative link w/o actually testing it. I've fixed the url above, but here it is, too: https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBRtest_installation_notes.md

**Comment by emiliom** [comment]
Just for reference, from https://github.com/ODM2/WOFpy/blob/master/docs/WOFpyODM2LBRtest_installation_notes.md, for a test deployment, `runserver.py` is passed arguments that look like this:
```
python runserver_odm2_timeseries.py --config=odm2_config_timeseries.cfg --connection=private_config
```

**Comment by emiliom** [comment]
A follow up clarification to an earlier comment from @lsetiawan:

> Maybe we shouldn't just copy the examples, but maybe copy actual configuration files depending on the users need to either deploy it as testing or production?

As described succinctly [here](72#issuecomment-295432274), there are **two** kinds of configuration files:
1. The `.cfg` file that's in `examples` and is used by `runserver.py`. Used by both test and production deployments.
2. Other configuration files used only in production deployments, and involving wsgi, linux init system (systemd & ?), and nginx

Don and I agree that it'd be very helpful to users if we created template/example files for the second set (in a new directory, somewhere), and if `wofpy_config.py` then copied them over to the right place if given a run-time argument of "production deployment".

There are two sets of

**Comment by emiliom** [comment]
Note to self and anyone else who looks at this issue: We've made lots of progress on the issues discussed here. This is being tracked mostly in issue #72

**Comment by emiliom** [comment]
For reference: this issue is largely or completely addressed already. We'll leave it open only until we've captured the changes in updated documentation.

**Comment by lsetiawan** [comment]
PR https://github.com/ODM2/WOFpy/pull/136 and https://github.com/ODM2/WOFpy/pull/141 closes this issues. More updated documentation is coming.
