### ISSUE TITLE
test_odm2_dao_sqlite is failing on master

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/WOFpy#99]
For future reference the last time this test passed was in https://travis-ci.org/ODM2/WOFpy/builds/194949742

**Comment by emiliom** [comment]
Related/dependent on #75

**Comment by emiliom** [comment]
@lsetiawan and @ocefpaf, we can close this issue, right? If so, please go ahead and close it. Reference the PR that fixed it, if you can find it easily.

**Comment by ocefpaf** [comment]
Yep. Forgot to xref in the PR.
